export const modules = {
  shell00: {
    id: 'shell00',
    title: 'Shell 00',
    version: '5.1',
    type: 'shell',
    order: 0,
    description: 'Introduction to shell basics: file manipulation, permissions, SSH keys, git, and shell commands.',
    summary: 'The basics of the Unix shell. Learn to create files with specific permissions, manage SSH keys, write shell scripts, and use core Unix commands.',
    exercises: [
      { id: 'ex00', title: 'Z', number: 0, description: "Create a file called 'z' that returns 'Z' followed by a new line when the cat command is used on it.", files: ['z'], type: 'shell' },
      { id: 'ex01', title: 'testShell00', number: 1, description: 'Create a file with specific attributes matching: -r--r-xr-x, size 40, timestamp Jun 1 23:42.', files: ['testShell00.tar'], type: 'shell' },
      { id: 'ex02', title: 'Oh yeah, mooore...', number: 2, description: 'Create files and directories with specific permissions and properties matching a given ls -l output.', files: ['exo2.tar'], type: 'shell' },
      { id: 'ex03', title: 'SSH me!', number: 3, description: 'Create an SSH key using ed25519 algorithm and save the public key.', files: ['id_ed25519_pub'], type: 'shell' },
      { id: 'ex04', title: 'midLS', number: 4, description: 'Write a command that lists files and directories sorted by modification date, comma-separated, directories ending with /.', files: ['midLS'], type: 'shell' },
      { id: 'ex05', title: 'GiT commit', number: 5, description: 'Create a shell script that outputs git log information with specific formatting.', files: ['git_commit.sh'], type: 'shell' },
      { id: 'ex06', title: 'gitignore', number: 6, description: 'List files ignored by git in the repository.', files: ['gitignore'], type: 'shell' },
      { id: 'ex07', title: 'diff', number: 7, description: 'Compare two files and show the differences.', files: ['diff'], type: 'shell' },
      { id: 'ex08', title: 'clean', number: 8, description: 'Write a command that finds and removes files ending with ~ or starting/ending with #.', files: ['clean'], type: 'shell' },
      { id: 'ex09', title: 'Illusions, not tricks, Michael...', number: 9, description: 'Create a magic file that detects specific file types using the file command.', files: ['ft_magic'], type: 'shell' },
    ],
  },
  shell01: {
    id: 'shell01',
    title: 'Shell 01',
    version: '8.1',
    type: 'shell',
    order: 1,
    description: 'Advanced shell scripting: environment variables, find, counting, MAC addresses, awk, and base conversions.',
    summary: 'Dive deeper into shell scripting. Work with environment variables, file searching, awk text processing, and shell arithmetic.',
    exercises: [
      { id: 'ex00', title: 'Exam', number: 0, description: 'Register for the exam event and project.', files: [], type: 'info' },
      { id: 'ex01', title: 'print_groups', number: 1, description: 'Display the list of groups for the user defined in FT_USER environment variable, comma-separated.', files: ['print_groups.sh'], type: 'shell' },
      { id: 'ex02', title: 'find_sh', number: 2, description: 'Search for all .sh files in current directory and subdirectories, display names without .sh extension.', files: ['find_sh.sh'], type: 'shell' },
      { id: 'ex03', title: 'count_files', number: 3, description: 'Count and display the total number of regular files and directories including the starting directory.', files: ['count_files.sh'], type: 'shell' },
      { id: 'ex04', title: 'MAC', number: 4, description: "Display your machine's MAC addresses, each followed by a line break.", files: ['MAC.sh'], type: 'shell' },
      { id: 'ex05', title: 'Can you create it?', number: 5, description: 'Create a file with a very special name containing special characters.', files: ["'\\?$*'MaRViN'*$?\\'"], type: 'shell' },
      { id: 'ex06', title: 'Skip', number: 6, description: 'Use awk to skip lines and display specific output.', files: ['skip.sh'], type: 'shell' },
      { id: 'ex07', title: 'r_dwssap', number: 7, description: 'Reverse and transform /etc/passwd output in a specific format.', files: ['r_dwssap.sh'], type: 'shell' },
      { id: 'ex08', title: 'add_chelou', number: 8, description: 'Perform arithmetic with numbers in different bases and display the result.', files: ['add_chelou.sh'], type: 'shell' },
    ],
  },
  c00: {
    id: 'c00',
    title: 'C 00',
    version: '8',
    type: 'c',
    order: 2,
    description: 'Introduction to C: basic output functions using write().',
    summary: 'Your first steps in C programming. Learn to write functions that output characters, strings, and numbers using only the write() system call.',
    exercises: [
      { id: 'ex00', title: 'ft_putchar', number: 0, description: 'Write a function that displays the character passed as a parameter.', prototype: 'void ft_putchar(char c);', allowed: ['write'], files: ['ft_putchar.c'], type: 'c' },
      { id: 'ex01', title: 'ft_print_alphabet', number: 1, description: 'Create a function that displays the alphabet in lowercase, on a single line, in ascending order.', prototype: 'void ft_print_alphabet(void);', allowed: ['ft_putchar'], files: ['ft_print_alphabet.c'], type: 'c' },
      { id: 'ex02', title: 'ft_print_reverse_alphabet', number: 2, description: 'Create a function that displays the alphabet in lowercase, on a single line, in descending order.', prototype: 'void ft_print_reverse_alphabet(void);', allowed: ['ft_putchar'], files: ['ft_print_reverse_alphabet.c'], type: 'c' },
      { id: 'ex03', title: 'ft_print_numbers', number: 3, description: 'Create a function that displays all digits, on a single line, in ascending order.', prototype: 'void ft_print_numbers(void);', allowed: ['ft_putchar'], files: ['ft_print_numbers.c'], type: 'c' },
      { id: 'ex04', title: 'ft_is_negative', number: 4, description: "Create a function that displays 'N' or 'P' depending on the integer's sign entered as a parameter.", prototype: 'void ft_is_negative(int n);', allowed: ['ft_putchar'], files: ['ft_is_negative.c'], type: 'c' },
      { id: 'ex05', title: 'ft_print_comb', number: 5, description: 'Create a function that displays all different combinations of three different digits in ascending order.', prototype: 'void ft_print_comb(void);', allowed: ['ft_putchar'], files: ['ft_print_comb.c'], type: 'c' },
      { id: 'ex06', title: 'ft_print_comb2', number: 6, description: 'Create a function that displays all different combinations of two two-digit numbers.', prototype: 'void ft_print_comb2(void);', allowed: ['ft_putchar'], files: ['ft_print_comb2.c'], type: 'c' },
      { id: 'ex07', title: 'ft_putnbr', number: 7, description: 'Create a function that displays the integer entered as a parameter. Must handle all possible int values.', prototype: 'void ft_putnbr(int nb);', allowed: ['ft_putchar'], files: ['ft_putnbr.c'], type: 'c' },
      { id: 'ex08', title: 'ft_print_combn', number: 8, description: 'Create a function that displays all different combinations of n numbers in ascending order. n between 0 and 10.', prototype: 'void ft_print_combn(int n);', allowed: ['ft_putchar'], files: ['ft_print_combn.c'], type: 'c' },
    ],
  },
  c01: {
    id: 'c01',
    title: 'C 01',
    version: '6',
    type: 'c',
    order: 3,
    description: 'Pointers and basic C operations.',
    summary: 'Master pointers and references. Learn to manipulate values through memory addresses, swap variables, and work with string lengths and integer arrays.',
    exercises: [
      { id: 'ex00', title: 'ft_ft', number: 0, description: 'Create a function that takes a pointer to int and sets the value to 42.', prototype: 'void ft_ft(int *nbr);', files: ['ft_ft.c'], type: 'c' },
      { id: 'ex01', title: 'ft_ultimate_ft', number: 1, description: 'Create a function that takes a pointer to pointer... (9 levels) to int and sets the value to 42.', prototype: 'void ft_ultimate_ft(int *********nbr);', files: ['ft_ultimate_ft.c'], type: 'c' },
      { id: 'ex02', title: 'ft_swap', number: 2, description: 'Create a function that swaps the value of two integers whose addresses are given as parameters.', prototype: 'void ft_swap(int *a, int *b);', files: ['ft_swap.c'], type: 'c' },
      { id: 'ex03', title: 'ft_div_mod', number: 3, description: 'Create a function that divides a by b and stores the result in the int pointed by div, and the remainder in mod.', prototype: 'void ft_div_mod(int a, int b, int *div, int *mod);', files: ['ft_div_mod.c'], type: 'c' },
      { id: 'ex04', title: 'ft_ultimate_div_mod', number: 4, description: 'Create a function that divides two integers and stores both result and remainder in the original variables.', prototype: 'void ft_ultimate_div_mod(int *a, int *b);', files: ['ft_ultimate_div_mod.c'], type: 'c' },
      { id: 'ex05', title: 'ft_putstr', number: 5, description: 'Create a function that displays a string of characters on the standard output.', prototype: 'void ft_putstr(char *str);', allowed: ['write'], files: ['ft_putstr.c'], type: 'c' },
      { id: 'ex06', title: 'ft_strlen', number: 6, description: 'Create a function that counts and returns the number of characters in a string.', prototype: 'int ft_strlen(char *str);', files: ['ft_strlen.c'], type: 'c' },
      { id: 'ex07', title: 'ft_rev_int_tab', number: 7, description: 'Create a function that reverses a given array of integers.', prototype: 'void ft_rev_int_tab(int *tab, int size);', files: ['ft_rev_int_tab.c'], type: 'c' },
      { id: 'ex08', title: 'ft_sort_int_tab', number: 8, description: 'Create a function that sorts an array of integers in ascending order.', prototype: 'void ft_sort_int_tab(int *tab, int size);', files: ['ft_sort_int_tab.c'], type: 'c' },
    ],
  },
  c02: {
    id: 'c02',
    title: 'C 02',
    version: '6',
    type: 'c',
    order: 4,
    description: 'String manipulation in C.',
    summary: 'Deep dive into string operations. Implement your own versions of standard C string functions: copy, check character types, case conversion, and more.',
    exercises: [
      { id: 'ex00', title: 'ft_strcpy', number: 0, description: 'Reproduce the behavior of strcpy.', prototype: 'char *ft_strcpy(char *dest, char *src);', files: ['ft_strcpy.c'], type: 'c' },
      { id: 'ex01', title: 'ft_strncpy', number: 1, description: 'Reproduce the behavior of strncpy.', prototype: 'char *ft_strncpy(char *dest, char *src, unsigned int n);', files: ['ft_strncpy.c'], type: 'c' },
      { id: 'ex02', title: 'ft_str_is_alpha', number: 2, description: 'Check if a string contains only alphabetical characters.', prototype: 'int ft_str_is_alpha(char *str);', files: ['ft_str_is_alpha.c'], type: 'c' },
      { id: 'ex03', title: 'ft_str_is_numeric', number: 3, description: 'Check if a string contains only digits.', prototype: 'int ft_str_is_numeric(char *str);', files: ['ft_str_is_numeric.c'], type: 'c' },
      { id: 'ex04', title: 'ft_str_is_lowercase', number: 4, description: 'Check if a string contains only lowercase characters.', prototype: 'int ft_str_is_lowercase(char *str);', files: ['ft_str_is_lowercase.c'], type: 'c' },
      { id: 'ex05', title: 'ft_str_is_uppercase', number: 5, description: 'Check if a string contains only uppercase characters.', prototype: 'int ft_str_is_uppercase(char *str);', files: ['ft_str_is_uppercase.c'], type: 'c' },
      { id: 'ex06', title: 'ft_str_is_printable', number: 6, description: 'Check if a string contains only printable characters.', prototype: 'int ft_str_is_printable(char *str);', files: ['ft_str_is_printable.c'], type: 'c' },
      { id: 'ex07', title: 'ft_strupcase', number: 7, description: 'Transform every letter to uppercase.', prototype: 'char *ft_strupcase(char *str);', files: ['ft_strupcase.c'], type: 'c' },
      { id: 'ex08', title: 'ft_strlowcase', number: 8, description: 'Transform every letter to lowercase.', prototype: 'char *ft_strlowcase(char *str);', files: ['ft_strlowcase.c'], type: 'c' },
      { id: 'ex09', title: 'ft_strcapitalize', number: 9, description: 'Capitalize the first letter of each word and lower the rest.', prototype: 'char *ft_strcapitalize(char *str);', files: ['ft_strcapitalize.c'], type: 'c' },
      { id: 'ex10', title: 'ft_strlcpy', number: 10, description: 'Reproduce the behavior of strlcpy.', prototype: 'unsigned int ft_strlcpy(char *dest, char *src, unsigned int size);', files: ['ft_strlcpy.c'], type: 'c' },
      { id: 'ex11', title: 'ft_putstr_non_printable', number: 11, description: 'Display a string, printing non-printable characters as hex.', prototype: 'void ft_putstr_non_printable(char *str);', allowed: ['write'], files: ['ft_putstr_non_printable.c'], type: 'c' },
      { id: 'ex12', title: 'ft_print_memory', number: 12, description: 'Display the memory area in a format similar to hexdump.', prototype: 'void *ft_print_memory(void *addr, unsigned int size);', allowed: ['write'], files: ['ft_print_memory.c'], type: 'c' },
    ],
  },
  c03: {
    id: 'c03',
    title: 'C 03',
    version: '5',
    type: 'c',
    order: 5,
    description: 'String comparison and concatenation.',
    summary: 'Implement string comparison and concatenation functions from scratch. Master the subtle differences between strcmp/strncmp and strcat/strncat.',
    exercises: [
      { id: 'ex00', title: 'ft_strcmp', number: 0, description: 'Reproduce the behavior of strcmp.', prototype: 'int ft_strcmp(char *s1, char *s2);', files: ['ft_strcmp.c'], type: 'c' },
      { id: 'ex01', title: 'ft_strncmp', number: 1, description: 'Reproduce the behavior of strncmp.', prototype: 'int ft_strncmp(char *s1, char *s2, unsigned int n);', files: ['ft_strncmp.c'], type: 'c' },
      { id: 'ex02', title: 'ft_strcat', number: 2, description: 'Reproduce the behavior of strcat.', prototype: 'char *ft_strcat(char *dest, char *src);', files: ['ft_strcat.c'], type: 'c' },
      { id: 'ex03', title: 'ft_strncat', number: 3, description: 'Reproduce the behavior of strncat.', prototype: 'char *ft_strncat(char *dest, char *src, unsigned int nb);', files: ['ft_strncat.c'], type: 'c' },
      { id: 'ex04', title: 'ft_strstr', number: 4, description: 'Reproduce the behavior of strstr.', prototype: 'char *ft_strstr(char *str, char *to_find);', files: ['ft_strstr.c'], type: 'c' },
      { id: 'ex05', title: 'ft_strlcat', number: 5, description: 'Reproduce the behavior of strlcat.', prototype: 'unsigned int ft_strlcat(char *dest, char *src, unsigned int size);', files: ['ft_strlcat.c'], type: 'c' },
    ],
  },
  c04: {
    id: 'c04',
    title: 'C 04',
    version: '5',
    type: 'c',
    order: 6,
    description: 'Numeric conversions: atoi and base conversions.',
    summary: 'Convert strings to integers and handle number representations in different bases. Build the foundation for understanding data parsing.',
    exercises: [
      { id: 'ex00', title: 'ft_strlen', number: 0, description: 'Create a function that returns the length of a string.', prototype: 'int ft_strlen(char *str);', files: ['ft_strlen.c'], type: 'c' },
      { id: 'ex01', title: 'ft_putstr', number: 1, description: 'Create a function that displays a string.', prototype: 'void ft_putstr(char *str);', allowed: ['write'], files: ['ft_putstr.c'], type: 'c' },
      { id: 'ex02', title: 'ft_putnbr', number: 2, description: 'Create a function that displays an integer.', prototype: 'void ft_putnbr(int nb);', allowed: ['write'], files: ['ft_putnbr.c'], type: 'c' },
      { id: 'ex03', title: 'ft_atoi', number: 3, description: 'Reproduce the behavior of atoi.', prototype: 'int ft_atoi(char *str);', files: ['ft_atoi.c'], type: 'c' },
      { id: 'ex04', title: 'ft_putnbr_base', number: 4, description: 'Display an integer in a given base.', prototype: 'void ft_putnbr_base(int nbr, char *base);', allowed: ['write'], files: ['ft_putnbr_base.c'], type: 'c' },
      { id: 'ex05', title: 'ft_atoi_base', number: 5, description: 'Convert a string from a given base to an integer.', prototype: 'int ft_atoi_base(char *str, char *base);', files: ['ft_atoi_base.c'], type: 'c' },
    ],
  },
  c05: {
    id: 'c05',
    title: 'C 05',
    version: '7',
    type: 'c',
    order: 7,
    description: 'Recursion and mathematical functions.',
    summary: 'Master recursion through mathematical problems: factorials, powers, Fibonacci, square roots, and prime numbers. The legendary Ten Queens problem awaits.',
    exercises: [
      { id: 'ex00', title: 'ft_iterative_factorial', number: 0, description: 'Create an iterative function that returns the factorial of a number.', prototype: 'int ft_iterative_factorial(int nb);', files: ['ft_iterative_factorial.c'], type: 'c' },
      { id: 'ex01', title: 'ft_recursive_factorial', number: 1, description: 'Create a recursive function that returns the factorial of a number.', prototype: 'int ft_recursive_factorial(int nb);', files: ['ft_recursive_factorial.c'], type: 'c' },
      { id: 'ex02', title: 'ft_iterative_power', number: 2, description: 'Create an iterative function that returns a power of a number.', prototype: 'int ft_iterative_power(int nb, int power);', files: ['ft_iterative_power.c'], type: 'c' },
      { id: 'ex03', title: 'ft_recursive_power', number: 3, description: 'Create a recursive function that returns a power of a number.', prototype: 'int ft_recursive_power(int nb, int power);', files: ['ft_recursive_power.c'], type: 'c' },
      { id: 'ex04', title: 'ft_fibonacci', number: 4, description: 'Create a function that returns the nth element of the Fibonacci sequence.', prototype: 'int ft_fibonacci(int index);', files: ['ft_fibonacci.c'], type: 'c' },
      { id: 'ex05', title: 'ft_sqrt', number: 5, description: 'Create a function that returns the integer square root of a number if it exists, otherwise 0.', prototype: 'int ft_sqrt(int nb);', files: ['ft_sqrt.c'], type: 'c' },
      { id: 'ex06', title: 'ft_is_prime', number: 6, description: 'Create a function that returns 1 if the number is prime, 0 otherwise.', prototype: 'int ft_is_prime(int nb);', files: ['ft_is_prime.c'], type: 'c' },
      { id: 'ex07', title: 'ft_find_next_prime', number: 7, description: 'Create a function that returns the next prime number greater or equal to the parameter.', prototype: 'int ft_find_next_prime(int nb);', files: ['ft_find_next_prime.c'], type: 'c' },
      { id: 'ex08', title: 'The Ten Queens', number: 8, description: 'Create a function that displays all possible placements of ten queens on a chessboard without conflict.', prototype: 'int ft_ten_queens_puzzle(void);', allowed: ['write'], files: ['ft_ten_queens_puzzle.c'], type: 'c' },
    ],
  },
  c06: {
    id: 'c06',
    title: 'C 06',
    version: '8',
    type: 'c',
    order: 8,
    description: 'Command-line arguments (argc and argv).',
    summary: 'Learn to work with program arguments. Parse argc/argv to process command-line input, print parameters, and sort them.',
    exercises: [
      { id: 'ex00', title: 'ft_print_program_name', number: 0, description: 'Write a program that displays its own name.', prototype: 'int main(int argc, char **argv);', allowed: ['write'], files: ['ft_print_program_name.c'], type: 'c' },
      { id: 'ex01', title: 'ft_print_params', number: 1, description: 'Write a program that displays its given arguments, one per line.', prototype: 'int main(int argc, char **argv);', allowed: ['write'], files: ['ft_print_params.c'], type: 'c' },
      { id: 'ex02', title: 'ft_rev_params', number: 2, description: 'Write a program that displays its given arguments in reverse order.', prototype: 'int main(int argc, char **argv);', allowed: ['write'], files: ['ft_rev_params.c'], type: 'c' },
      { id: 'ex03', title: 'ft_sort_params', number: 3, description: 'Write a program that displays its given arguments sorted in ASCII order.', prototype: 'int main(int argc, char **argv);', allowed: ['write'], files: ['ft_sort_params.c'], type: 'c' },
    ],
  },
  c07: {
    id: 'c07',
    title: 'C 07',
    version: '6',
    type: 'c',
    order: 9,
    description: 'Dynamic memory allocation (malloc).',
    summary: 'Enter the world of heap memory. Allocate, manipulate, and free memory dynamically. Build powerful tools like string duplication, range generation, and string splitting.',
    exercises: [
      { id: 'ex00', title: 'ft_strdup', number: 0, description: 'Reproduce the behavior of strdup using malloc.', prototype: 'char *ft_strdup(char *src);', allowed: ['malloc'], files: ['ft_strdup.c'], type: 'c' },
      { id: 'ex01', title: 'ft_range', number: 1, description: 'Create a function that returns an array of int containing all values between min and max.', prototype: 'int *ft_range(int min, int max);', allowed: ['malloc'], files: ['ft_range.c'], type: 'c' },
      { id: 'ex02', title: 'ft_ultimate_range', number: 2, description: 'Create a function that allocates and returns a range. Store the size in the parameter.', prototype: 'int ft_ultimate_range(int **range, int min, int max);', allowed: ['malloc'], files: ['ft_ultimate_range.c'], type: 'c' },
      { id: 'ex03', title: 'ft_strjoin', number: 3, description: 'Concatenate all the strings in strs, separated by sep. If size is 0, return an empty, freeable string.', prototype: 'char *ft_strjoin(int size, char **strs, char *sep);', allowed: ['malloc'], files: ['ft_strjoin.c'], type: 'c' },
      { id: 'ex04', title: 'ft_convert_base', number: 4, description: 'Create a function that converts a number from one base to another.', prototype: 'char *ft_convert_base(char *nbr, char *base_from, char *base_to);', allowed: ['malloc'], files: ['ft_convert_base.c'], type: 'c' },
      { id: 'ex05', title: 'ft_split', number: 5, description: 'Create a function that splits a string according to a charset.', prototype: 'char **ft_split(char *str, char *charset);', allowed: ['malloc'], files: ['ft_split.c'], type: 'c' },
    ],
  },
  c08: {
    id: 'c08',
    title: 'C 08',
    version: '14',
    type: 'c',
    order: 10,
    description: 'Header files, structs, and type definitions.',
    summary: 'Organize your code properly. Create header files, define structures, and manage multi-file projects. Build a linked list structure and learn to display it.',
    exercises: [
      { id: 'ex00', title: 'ft.h', number: 0, description: 'Create a header file ft.h that contains prototypes for various functions.', files: ['ft.h'], type: 'c' },
      { id: 'ex01', title: 'ft_boolean.h', number: 1, description: 'Create a header file ft_boolean.h that defines TRUE, FALSE, and related types.', files: ['ft_boolean.h'], type: 'c' },
      { id: 'ex02', title: 'ft_abs.h', number: 2, description: 'Create a macro ABS() that replaces its argument with the absolute value.', files: ['ft_abs.h'], type: 'c' },
      { id: 'ex03', title: 'ft_point.h', number: 3, description: 'Create a header file defining a t_point structure.', files: ['ft_point.h'], type: 'c' },
      { id: 'ex04', title: 'ft_strs_to_tab', number: 4, description: 'Create a function that transforms an array of strings into an array of structures.', allowed: ['malloc'], files: ['ft_strs_to_tab.c'], type: 'c' },
      { id: 'ex05', title: 'ft_show_tab', number: 5, description: 'Create a function that displays the content of an array of structures.', allowed: ['write'], files: ['ft_show_tab.c'], type: 'c' },
    ],
  },
  c09: {
    id: 'c09',
    title: 'C 09',
    version: '5.0',
    type: 'c',
    order: 11,
    description: 'Static library and Makefile.',
    summary: 'Learn the professional way to organize C projects. Create a static library (libft) with your reusable functions, a proper Makefile, and a recursive ft_split.',
    exercises: [
      { id: 'ex00', title: 'libft', number: 0, description: 'Create a static library libft.a containing useful functions.', files: ['libft.a'], type: 'c' },
      { id: 'ex01', title: 'Makefile', number: 1, description: 'Create a Makefile that compiles the libft library.', files: ['Makefile'], type: 'c' },
      { id: 'ex02', title: 'ft_split', number: 2, description: 'Create a recursive implementation of ft_split.', prototype: 'char **ft_split(char *str, char *charset);', allowed: ['malloc'], files: ['ft_split.c'], type: 'c' },
    ],
  },
  c10: {
    id: 'c10',
    title: 'C 10',
    version: '4.0',
    type: 'c',
    order: 12,
    description: 'File handling with open, read, write, close.',
    summary: 'Recreate classic Unix file utilities in C. Read files byte by byte with the raw syscalls, then rebuild cat, tail, and hexdump from scratch.',
    exercises: [
      { id: 'ex00', title: 'ft_display_file', number: 0, description: 'Display the content of the file whose name is given as a parameter. Print an error message if it fails.', prototype: 'int main(int argc, char **argv);', allowed: ['open', 'read', 'write', 'close'], files: ['ft_display_file.c'], type: 'c' },
      { id: 'ex01', title: 'ft_cat', number: 1, description: 'Reproduce the behavior of the cat command: print each file given as a parameter, or read stdin if none is given.', prototype: 'int main(int argc, char **argv);', allowed: ['open', 'read', 'write', 'close'], files: ['ft_cat.c'], type: 'c' },
      { id: 'ex02', title: 'ft_tail', number: 2, description: "Reproduce 'tail -c N': print only the last N bytes of each file given as a parameter, usage: ./ft_tail -c N file1 file2 ...", prototype: 'int main(int argc, char **argv);', allowed: ['open', 'read', 'write', 'close'], files: ['ft_tail.c'], type: 'c' },
      { id: 'ex03', title: 'ft_hexdump', number: 3, description: "Reproduce 'hexdump -C': print the content of each file given as a parameter as a hex + ASCII dump, 16 bytes per line.", prototype: 'int main(int argc, char **argv);', allowed: ['open', 'read', 'write', 'close', 'malloc'], files: ['ft_hexdump.c'], type: 'c' },
    ],
  },
  c11: {
    id: 'c11',
    title: 'C 11',
    version: '8.0',
    type: 'c',
    order: 13,
    description: 'Function pointers.',
    summary: 'Unlock the power of callbacks. Use function pointers to create generic functions: for_each, map, any, count_if. Build a simple calculator with function pointer dispatch.',
    exercises: [
      { id: 'ex00', title: 'ft_foreach', number: 0, description: 'Apply a function to each element of an integer array.', prototype: 'void ft_foreach(int *tab, int length, void(*f)(int));', files: ['ft_foreach.c'], type: 'c' },
      { id: 'ex01', title: 'ft_map', number: 1, description: 'Apply a function to each element of an array and return a new array.', prototype: 'int *ft_map(int *tab, int length, int(*f)(int));', allowed: ['malloc'], files: ['ft_map.c'], type: 'c' },
      { id: 'ex02', title: 'ft_any', number: 2, description: 'Return 1 if at least one element in the array makes the function return a non-zero value.', prototype: 'int ft_any(char **tab, int(*f)(char*));', files: ['ft_any.c'], type: 'c' },
      { id: 'ex03', title: 'ft_count_if', number: 3, description: 'Count the number of elements in the array for which the function returns a non-zero value.', prototype: 'int ft_count_if(char **tab, int length, int(*f)(char*));', files: ['ft_count_if.c'], type: 'c' },
      { id: 'ex04', title: 'ft_is_sort', number: 4, description: 'Return 1 if the array is sorted, 0 otherwise.', prototype: 'int ft_is_sort(int *tab, int length, int(*f)(int, int));', files: ['ft_is_sort.c'], type: 'c' },
      { id: 'ex05', title: 'do-op', number: 5, description: 'Write a program that performs a mathematical operation on two integers.', prototype: 'int main(int argc, char **argv);', allowed: ['write', 'atoi'], files: ['do-op.c'], type: 'c' },
      { id: 'ex06', title: 'ft_sort_string_tab', number: 6, description: 'Sort an array of strings by ASCII order.', prototype: 'void ft_sort_string_tab(char **tab);', files: ['ft_sort_string_tab.c'], type: 'c' },
      { id: 'ex07', title: 'ft_advanced_sort_string_tab', number: 7, description: 'Sort an array of strings using a comparison function.', prototype: 'void ft_advanced_sort_string_tab(char **tab, int(*cmp)(char *, char *));', files: ['ft_advanced_sort_string_tab.c'], type: 'c' },
    ],
  },
}

export type Module = (typeof modules)[keyof typeof modules]
export type Exercise = Module['exercises'][number]

export type ModuleType = 'shell' | 'c'

export const moduleOrder = ['shell00', 'shell01', 'c00', 'c01', 'c02', 'c03', 'c04', 'c05', 'c06', 'c07', 'c08', 'c09', 'c10', 'c11']
