import { NextResponse } from "next/server";

export async function GET() {
  const sql = `
-- User progress across modules
CREATE TABLE IF NOT EXISTS user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  module_id TEXT NOT NULL,
  exercise_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'done',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, module_id, exercise_id)
);

-- Exam attempt history
CREATE TABLE IF NOT EXISTS exam_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  week_id TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'editor',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ,
  duration_seconds INTEGER DEFAULT 0,
  result TEXT DEFAULT 'active',
  final_grade REAL DEFAULT 0,
  levels JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Exam preparation: which weeks have been reviewed
CREATE TABLE IF NOT EXISTS exam_prep (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  week_id TEXT NOT NULL,
  reviewed BOOLEAN DEFAULT false,
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, week_id)
);

-- Exam preparation: which exercises have been seen/practiced
CREATE TABLE IF NOT EXISTS exam_prep_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  week_id TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 0,
  exercise_name TEXT NOT NULL,
  done BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, week_id, level, exercise_name)
);

-- Enable Row Level Security
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_prep ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_prep_exercises ENABLE ROW LEVEL SECURITY;

-- RLS policies: users can only access their own data
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their progress' AND tablename = 'user_progress') THEN
    CREATE POLICY "Users can manage their progress" ON user_progress FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their exam history' AND tablename = 'exam_history') THEN
    CREATE POLICY "Users can manage their exam history" ON exam_history FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their exam prep' AND tablename = 'exam_prep') THEN
    CREATE POLICY "Users can manage their exam prep" ON exam_prep FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their prep exercises' AND tablename = 'exam_prep_exercises') THEN
    CREATE POLICY "Users can manage their prep exercises" ON exam_prep_exercises FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;
  `.trim();

  return NextResponse.json({
    message: "Copy this SQL into your Supabase SQL Editor: https://julmcohcipklgseecize.supabase.co/project/default/sql/new",
    sql,
  });
}
