import { NextResponse } from "next/server";
import { Pool } from "pg";

const SQL = `
CREATE TABLE IF NOT EXISTS user_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  module_id TEXT NOT NULL,
  exercise_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'done',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, module_id, exercise_id)
);

CREATE TABLE IF NOT EXISTS exam_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  week_id TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'editor',
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ,
  duration_seconds INTEGER DEFAULT 0,
  result TEXT DEFAULT 'active',
  final_grade REAL DEFAULT 0,
  levels JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exam_prep (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  week_id TEXT NOT NULL,
  reviewed BOOLEAN DEFAULT false,
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, week_id)
);

CREATE TABLE IF NOT EXISTS exam_prep_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  week_id TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 0,
  exercise_name TEXT NOT NULL,
  done BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, week_id, level, exercise_name)
);

CREATE TABLE IF NOT EXISTS normal_days_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  module_id TEXT NOT NULL,
  exercise_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'done',
  code TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, module_id, exercise_id)
);

CREATE TABLE IF NOT EXISTS user_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  theme TEXT DEFAULT 'system',
  visitor_id TEXT,
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_prep ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_prep_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE normal_days_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their progress') THEN
    CREATE POLICY "Users can manage their progress" ON user_progress FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their exam history') THEN
    CREATE POLICY "Users can manage their exam history" ON exam_history FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their exam prep') THEN
    CREATE POLICY "Users can manage their exam prep" ON exam_prep FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their prep exercises') THEN
    CREATE POLICY "Users can manage their prep exercises" ON exam_prep_exercises FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their normal days progress') THEN
    CREATE POLICY "Users can manage their normal days progress" ON normal_days_progress FOR ALL USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their settings') THEN
    CREATE POLICY "Users can manage their settings" ON user_settings FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;
`;

export async function GET() {
  const connStr = process.env.DATABASE_URL || "postgresql://postgres.julmcohcipklgseecize:G3fInDxoApsKYEP9@aws-0-eu-west-3.pooler.supabase.co:6543/postgres?sslmode=require";
  
  console.log("Trying connection via pooler...");
  
  let pool: Pool | null = null;
  
  // Try pooler first (works on Vercel), fall back to direct
  const connStrings = [
    "postgresql://postgres.julmcohcipklgseecize:G3fInDxoApsKYEP9@aws-0-eu-west-3.pooler.supabase.co:6543/postgres?sslmode=require",
    connStr,
  ];

  const results: string[] = [];
  let connected = false;

  for (const cs of connStrings) {
    try {
      pool = new Pool({
        connectionString: cs,
        ssl: { rejectUnauthorized: false },
        connectionTimeoutMillis: 10000,
      });
      await pool.query("SELECT 1");
      connected = true;
      results.push(`✓ Connected via ${new URL(cs.replace("postgresql://", "https://")).hostname}`);
      break;
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      results.push(`✗ Failed: ${msg.slice(0, 80)}`);
      if (pool) {
        await pool.end().catch(() => {});
        pool = null;
      }
    }
  }

  if (!connected || !pool) {
    return NextResponse.json({ success: false, results, error: "Could not connect to database" });
  }

  const execResults: string[] = [];

  for (const stmt of SQL.split(";").map((s) => s.trim()).filter(Boolean)) {
    try {
      await pool.query(stmt + ";");
      execResults.push(`✓ ${stmt.slice(0, 60)}...`);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      if (!msg.includes("already exists") && !msg.includes("duplicate")) {
        execResults.push(`✗ ${stmt.slice(0, 60)}: ${msg}`);
      } else {
        execResults.push(`✓ ${stmt.slice(0, 60)} (already exists)`);
      }
    }
  }

  await pool.end();

  return NextResponse.json({ success: true, results: execResults });
}
