import { NextResponse } from "next/server";
import { Pool } from "pg";

const SQL = `
CREATE TABLE IF NOT EXISTS user_progress (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, module_id TEXT NOT NULL, exercise_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'done', updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(user_id, module_id, exercise_id));
CREATE TABLE IF NOT EXISTS exam_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, week_id TEXT NOT NULL, mode TEXT NOT NULL DEFAULT 'editor', started_at TIMESTAMPTZ NOT NULL DEFAULT now(), ended_at TIMESTAMPTZ, duration_seconds INTEGER DEFAULT 0, result TEXT DEFAULT 'active', final_grade REAL DEFAULT 0, levels JSONB DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS exam_prep (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, week_id TEXT NOT NULL, reviewed BOOLEAN DEFAULT false, updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(user_id, week_id));
CREATE TABLE IF NOT EXISTS exam_prep_exercises (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, week_id TEXT NOT NULL, level INTEGER NOT NULL DEFAULT 0, exercise_name TEXT NOT NULL, done BOOLEAN DEFAULT true, updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(user_id, week_id, level, exercise_name));
CREATE TABLE IF NOT EXISTS normal_days_progress (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, module_id TEXT NOT NULL, exercise_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'done', code TEXT DEFAULT '', updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(user_id, module_id, exercise_id));
CREATE TABLE IF NOT EXISTS user_settings (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE, theme TEXT DEFAULT 'system', visitor_id TEXT, updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS exam_sessions (token TEXT PRIMARY KEY, data JSONB NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS exam_sessions_expires_at_idx ON exam_sessions (expires_at);
CREATE TABLE IF NOT EXISTS exam_visitor_attempts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, visitor_id TEXT NOT NULL, data JSONB NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS exam_visitor_attempts_visitor_id_idx ON exam_visitor_attempts (visitor_id);
CREATE TABLE IF NOT EXISTS online_visitors (visitor_id TEXT PRIMARY KEY, last_seen TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS online_visitors_last_seen_idx ON online_visitors (last_seen);

-- exam_sessions / exam_visitor_attempts / online_visitors are server-only
-- (accessed via a direct Postgres connection with DATABASE_URL, never from
-- the browser via the Supabase client), so they don't need RLS policies.

ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_prep ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_prep_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE normal_days_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users own progress') THEN CREATE POLICY "Users own progress" ON user_progress FOR ALL USING (auth.uid() = user_id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users own exam history') THEN CREATE POLICY "Users own exam history" ON exam_history FOR ALL USING (auth.uid() = user_id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users own exam prep') THEN CREATE POLICY "Users own exam prep" ON exam_prep FOR ALL USING (auth.uid() = user_id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users own prep exercises') THEN CREATE POLICY "Users own prep exercises" ON exam_prep_exercises FOR ALL USING (auth.uid() = user_id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users own normal progress') THEN CREATE POLICY "Users own normal progress" ON normal_days_progress FOR ALL USING (auth.uid() = user_id); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users own settings') THEN CREATE POLICY "Users own settings" ON user_settings FOR ALL USING (auth.uid() = user_id); END IF;
END $$;
`;

// One-time/idempotent schema setup, gated behind DB_MIGRATE_SECRET so it
// isn't a public unauthenticated endpoint that runs DDL against the
// database. Uses DATABASE_URL (already configured for the rest of the app)
// instead of a hardcoded credential + a guessed list of pooler hosts.
export async function GET(request: Request) {
  const secret = new URL(request.url).searchParams.get("secret");
  if (!process.env.DB_MIGRATE_SECRET || secret !== process.env.DB_MIGRATE_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!process.env.DATABASE_URL) {
    return NextResponse.json({ error: "DATABASE_URL is not configured" }, { status: 500 });
  }

  const results: string[] = [];
  const pool = new Pool({
    // Strip ?sslmode=require — pg's newer versions treat it as verify-full,
    // which fails against Supabase's pooler cert chain. ssl below replaces it.
    connectionString: process.env.DATABASE_URL.split("?")[0],
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 8000,
    max: 1,
  });

  try {
    await pool.query("SELECT 1");

    for (const stmt of SQL.split(";").map((s) => s.trim()).filter(Boolean)) {
      try {
        await pool.query(stmt + ";");
        results.push(`  ✓ ${stmt.slice(0, 50)}...`);
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        if (msg.includes("already exists") || msg.includes("duplicate")) {
          results.push(`  ✓ ${stmt.slice(0, 50)} (exists)`);
        } else {
          results.push(`  ✗ ${msg.slice(0, 100)}`);
        }
      }
    }

    return NextResponse.json({ success: true, results });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({
      success: false,
      error: msg.slice(0, 200),
      help: "Run SQL manually: https://julmcohcipklgseecize.supabase.co/project/default/sql/new",
    });
  } finally {
    await pool.end().catch(() => {});
  }
}
