export type Status = 'Done' | 'Available' | 'Not recommended' | 'Unavailable (locked)'
export type Project = {
  id: number
  name: string
  slug: string
  xp: number
  status: Status
  categories: string[]
  requires: string[]
  unlocks: string[]
  isRoot: boolean
  topic: string
  catInferred: boolean
}

export const CATEGORY_ORDER = [
  'Algo & AI & Data',
  'Core Curriculum',
  'Cryptography & Maths',
  'Development',
  'Devops',
  'Graphics & Gaming',
  'Professional Experience',
  'Security',
  'System & Kernel',
  'Web & Mobile',
  'Uncategorized',
]

export const CATEGORY_COLORS: Record<string, string> = {
  'Algo & AI & Data': '#c96a1f',
  'Core Curriculum': '#8f95a8',
  'Cryptography & Maths': '#2a5fd6',
  Development: '#0f8f6f',
  Devops: '#9c7a10',
  'Graphics & Gaming': '#8a4fd6',
  'Professional Experience': '#d64f8a',
  Security: '#d63b3b',
  'System & Kernel': '#3b8fd6',
  'Web & Mobile': '#3bb08f',
  Uncategorized: '#6b7080',
}

export const STATUS_ORDER: Record<Status, number> = {
  Done: 0,
  Available: 1,
  'Not recommended': 2,
  'Unavailable (locked)': 3,
}

/* Real data snapshot from the 42 intra Holy Graph (42cursus) */
export const projects: Project[] = [
  {
    id: 2623,
    name: '42_Collaborative_resume',
    slug: '42-collaborative-resume',
    xp: 2100,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Build your communication and self-reflection skills by working closely with a peer: through mutual interviews, learn to recognize and express both your strengths and theirs, crafting genuine, effective resumes.`,
    catInferred: false,
  },
  {
    id: 1387,
    name: '42run',
    slug: '42run',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['scop'],
    unlocks: [''],
    isRoot: false,
    topic: `Like the mobile game Temple Run — settle and create it on your own. An OpenGL project: graphic game using GPU power, 3D meshes, and classic gameplay features.`,
    catInferred: false,
  },
  {
    id: 1854,
    name: '42sh',
    slug: '42sh',
    xp: 15750,
    status: 'Available' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create a complete shell, from a minimum feature set up to job control and shell scripting, involving a large variety of standard UNIX/POSIX functionality.`,
    catInferred: false,
  },
  {
    id: 2688,
    name: 'A-Maze-ing',
    slug: 'a-maze-ing',
    xp: 1142,
    status: 'Unavailable (locked)' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create your own program that generates a fully usable maze compliant with several constraints, and display it.`,
    catInferred: true,
  },
  {
    id: 2371,
    name: 'Abstract_data',
    slug: 'abstract-data',
    xp: 20084,
    status: 'Unavailable (locked)' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `The multiple available containers in C++ all have a very different usage. To make sure you understand them all, re-implement them.`,
    catInferred: false,
  },
  {
    id: 2703,
    name: 'Agent Smith',
    slug: 'agent-smith',
    xp: 10042,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This is a project where you build an autonomous AI agent capable of reasoning, generating, executing, and iterating on code to solve programming challenges in a secure, sandboxed environment.`,
    catInferred: true,
  },
  {
    id: 2743,
    name: 'Agent smith',
    slug: 'agent-smith-2',
    xp: 10042,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['RAG against the machine'],
    unlocks: [''],
    isRoot: false,
    topic: `This is a project where you build an autonomous AI agent capable of reasoning, generating, executing, and iterating on code to solve programming challenges in a secure, sandboxed environment.`,
    catInferred: true,
  },
  {
    id: 2606,
    name: 'B',
    slug: 'b',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Uncategorized'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `The letter before C.`,
    catInferred: false,
  },
  {
    id: 2071,
    name: 'Bgp At Doors of Autonomous Systems is Simple',
    slug: 'bgp-at-doors-of-autonomous-systems-is-simple',
    xp: 22450,
    status: 'Available' as Status,
    categories: ['Devops'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Deepen your knowledge of NetPractice: simulate several networks (VXLAN+BGP-EVPN) in GNS3.`,
    catInferred: false,
  },
  {
    id: 1994,
    name: 'Born2beroot',
    slug: 'born2beroot',
    xp: 577,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project aims to introduce you to the wonderful world of virtualization.`,
    catInferred: false,
  },
  {
    id: 2686,
    name: 'Born2beroot',
    slug: 'born2beroot-2',
    xp: 577,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project aims to introduce you to the wonderful world of virtualization.`,
    catInferred: false,
  },
  {
    id: 1338,
    name: 'CPP Module 00',
    slug: 'cpp-module-00',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This first module of C++ is designed to help you understand the specificities of the language compared to C. Time to dive into Object-Oriented Programming.`,
    catInferred: false,
  },
  {
    id: 1339,
    name: 'CPP Module 01',
    slug: 'cpp-module-01',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand memory allocation, references, pointers to members, and the usage of the switch statement in C++.`,
    catInferred: false,
  },
  {
    id: 1340,
    name: 'CPP Module 02',
    slug: 'cpp-module-02',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand ad-hoc polymorphism, function overloading, and orthodox canonical classes in C++.`,
    catInferred: false,
  },
  {
    id: 1341,
    name: 'CPP Module 03',
    slug: 'cpp-module-03',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand inheritance in C++.`,
    catInferred: false,
  },
  {
    id: 1342,
    name: 'CPP Module 04',
    slug: 'cpp-module-04',
    xp: 9660,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand subtype polymorphism, abstract classes, and interfaces in C++.`,
    catInferred: false,
  },
  {
    id: 1343,
    name: 'CPP Module 05',
    slug: 'cpp-module-05',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand try/catch and exceptions in C++.`,
    catInferred: false,
  },
  {
    id: 1344,
    name: 'CPP Module 06',
    slug: 'cpp-module-06',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand the different types of casting in C++.`,
    catInferred: false,
  },
  {
    id: 1345,
    name: 'CPP Module 07',
    slug: 'cpp-module-07',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand templates in C++.`,
    catInferred: false,
  },
  {
    id: 1346,
    name: 'CPP Module 08',
    slug: 'cpp-module-08',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand templated containers, iterators, and algorithms in C++.`,
    catInferred: false,
  },
  {
    id: 2309,
    name: 'CPP Module 09',
    slug: 'cpp-module-09',
    xp: 10042,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This module is designed to help you understand containers in C++.`,
    catInferred: false,
  },
  {
    id: 2745,
    name: 'Call Me Maybe',
    slug: 'call-me-maybe',
    xp: 1764,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: ['RAG against the machine'],
    isRoot: true,
    topic: `This project introduces function calling in Large Language Models by building a system that translates natural language prompts into structured function calls with typed arguments. You'll implement constrained decoding to guarantee valid JSON output with a small 0.5B parameter model.`,
    catInferred: true,
  },
  {
    id: 2689,
    name: 'Call Me Maybe',
    slug: 'call-me-maybe-2',
    xp: 1764,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project introduces function calling in Large Language Models by building a system that translates natural language prompts into structured function calls with typed arguments. You'll implement constrained decoding to guarantee valid JSON output with a small 0.5B parameter model.`,
    catInferred: true,
  },
  {
    id: 1957,
    name: 'City Life',
    slug: 'city-life',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?5591'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to geospatial analytics: GeoPandas, clustering, making maps.`,
    catInferred: true,
  },
  {
    id: 2704,
    name: 'Codexion',
    slug: 'codexion',
    xp: 1764,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master concurrent programming in C through a simulation where coders race against burnout while competing for scarce USB dongles. Implement POSIX threads, mutexes, condition variables, and scheduling algorithms (FIFO/EDF) to prevent deadlocks and ensure fair access.`,
    catInferred: true,
  },
  {
    id: 2346,
    name: 'Cybersecurity',
    slug: 'cybersecurity',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Security'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important time in your cursus, during which you learn a new language, or even a new paradigm.`,
    catInferred: false,
  },
  {
    id: 2751,
    name: 'Datomic',
    slug: 'datomic',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Datomic is a databases project. On a single self-contained VM you climb twenty levels across six engines (SQLite, PostgreSQL, Redis, ClickHouse, Neo4j and DuckDB), building up SQL and then moving on to columnar, key-value and graph stores. The point is not the syntax of six databases but knowing which tool fits which problem, and federating them instead of duplicating data. Every level hands you a fresh, validated problem, so no two cadets get the same statement. You discover the SQL yourself in a browser playground and prove it in a live review exam.`,
    catInferred: true,
  },
  {
    id: 2708,
    name: 'Exam Rank 02',
    slug: 'exam-rank-02',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 1320,
    name: 'Exam Rank 02',
    slug: 'exam-rank-02-2',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 2709,
    name: 'Exam Rank 03',
    slug: 'exam-rank-03',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 1321,
    name: 'Exam Rank 03',
    slug: 'exam-rank-03-2',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 2710,
    name: 'Exam Rank 04',
    slug: 'exam-rank-04',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 1322,
    name: 'Exam Rank 04',
    slug: 'exam-rank-04-2',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 2711,
    name: 'Exam Rank 05',
    slug: 'exam-rank-05',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 1323,
    name: 'Exam Rank 05',
    slug: 'exam-rank-05-2',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 2712,
    name: 'Exam Rank 06',
    slug: 'exam-rank-06',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 1324,
    name: 'Exam Rank 06',
    slug: 'exam-rank-06-2',
    xp: 0,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: ['taskmaster'],
    isRoot: true,
    topic: ``,
    catInferred: false,
  },
  {
    id: 2008,
    name: 'FdF',
    slug: 'fdf',
    xp: 1000,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Discover graphic programming: open a graphics window and draw inside. FdF offers to represent 'iron wire' meshing in 3D.`,
    catInferred: false,
  },
  {
    id: 2705,
    name: 'Fly-in',
    slug: 'fly-in',
    xp: 2646,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Design an efficient drone routing system that navigates multiple autonomous drones through a dynamic network. A Python project: custom pathfinding handling simultaneous movement, zone occupancy rules, movement costs and conflict resolution.`,
    catInferred: true,
  },
  {
    id: 1960,
    name: 'Fried eggs',
    slug: 'fried-eggs',
    xp: 25200,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?1959'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to Deep Learning and computer vision (CNN, instance segmentation, object detection, data labeling).`,
    catInferred: true,
  },
  {
    id: 2225,
    name: 'Ftl_quantum',
    slug: 'ftl-quantum',
    xp: 6500,
    status: 'Available' as Status,
    categories: ['Cryptography & Maths'],
    requires: [''],
    unlocks: ['Supercharge'],
    isRoot: true,
    topic: `An introduction to quantum programming: create different quantum programs and run them on a real quantum computer.`,
    catInferred: true,
  },
  {
    id: 1983,
    name: 'Inception',
    slug: 'inception',
    xp: 15836,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Broaden your system administration skills with Docker: set up a complete infrastructure using Docker Compose, managing containerized services (NGINX with SSL/TLS, WordPress with php-fpm, MariaDB) inside your own VM.`,
    catInferred: false,
  },
  {
    id: 2746,
    name: 'Inception of context',
    slug: 'inception-of-context',
    xp: 0,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Build your own local AI coding assistant end to end on your laptop: a local model, a vector index over your code, a retriever that answers grounded questions, and a patch loop that applies, validates, and rolls back when things break. No cloud, no API key.`,
    catInferred: true,
  },
  {
    id: 2750,
    name: 'Inception of wisdom',
    slug: 'inception-of-wisdom',
    xp: 0,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Autonomous self-healing on your laptop: an agent watches a real service, notices when it crashes, retrieves relevant code/config from its own index, asks a local model what to change, applies the patch, commits, restarts, and rolls back if the fix doesn't take. Combines GitOps deployment (Inception-of-Things) with retrieval-augmented patching (Inception-of-Context).`,
    catInferred: true,
  },
  {
    id: 2064,
    name: 'Inception-of-Things',
    slug: 'inception-of-things',
    xp: 25450,
    status: 'Available' as Status,
    categories: ['Devops'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project introduces you to Kubernetes from a developer's perspective. You will set up small clusters and discover the mechanics of continuous integration, ending with a working cluster in Docker and a usable CI pipeline.`,
    catInferred: false,
  },
  {
    id: 2320,
    name: 'Java Module 00',
    slug: 'java-module-00',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this first module, you will learn the basics of solving both trivial and more challenging business tasks using basic Java language constructs.`,
    catInferred: false,
  },
  {
    id: 2321,
    name: 'Java Module 01',
    slug: 'java-module-01',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module, you will learn how to model the operation of various collections correctly, and create a full-scale money transfer application.`,
    catInferred: false,
  },
  {
    id: 2322,
    name: 'Java Module 02',
    slug: 'java-module-02',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will learn how to use input/output in Java and implement programs to manipulate a file system.`,
    catInferred: false,
  },
  {
    id: 2329,
    name: 'Java Module 03',
    slug: 'java-module-03',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will learn how to use basic multithreading mechanisms in Java.`,
    catInferred: false,
  },
  {
    id: 2330,
    name: 'Java Module 04',
    slug: 'java-module-04',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will learn to create library archives and use external libraries.`,
    catInferred: false,
  },
  {
    id: 2331,
    name: 'Java Module 05',
    slug: 'java-module-05',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will use the key mechanisms to work with the PostgreSQL DBMS via JDBC.`,
    catInferred: false,
  },
  {
    id: 2332,
    name: 'Java Module 06',
    slug: 'java-module-06',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will learn the basics of module and integration testing.`,
    catInferred: false,
  },
  {
    id: 2333,
    name: 'Java Module 07',
    slug: 'java-module-07',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will develop your own frameworks using reflection and annotation mechanisms.`,
    catInferred: false,
  },
  {
    id: 2334,
    name: 'Java Module 08',
    slug: 'java-module-08',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In this module you will learn about enterprise-level Java development and the basics of the Spring framework.`,
    catInferred: false,
  },
  {
    id: 2335,
    name: 'Java Module 09',
    slug: 'java-module-09',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: ['avaj-launcher", "fwa'],
    isRoot: true,
    topic: `In this module you will implement the basic mechanism of a client/server application based on the Java Sockets API.`,
    catInferred: false,
  },
  {
    id: 2372,
    name: 'Leaffliction',
    slug: 'leaffliction',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `An innovative computer vision project utilizing leaf image analysis for disease recognition.`,
    catInferred: false,
  },
  {
    id: 2551,
    name: 'Learn2Slither',
    slug: 'learn2slither',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A cutting-edge Q-learning project focused on autonomous decision-making in a dynamic environment.`,
    catInferred: true,
  },
  {
    id: 1314,
    name: 'Libft',
    slug: 'libft',
    xp: 462,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project is your very first project as a learner at 42. You will need to recode a few functions from the C standard library, plus other utility functions used throughout your whole curriculum.`,
    catInferred: false,
  },
  {
    id: 2373,
    name: 'Microshop',
    slug: 'microshop',
    xp: 24360,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['ft_microservices'],
    unlocks: [''],
    isRoot: false,
    topic: `Master creating microservice applications and deploying them to the Cloud using the Micronaut framework and various Oracle technologies.`,
    catInferred: true,
  },
  {
    id: 2355,
    name: 'Mobile',
    slug: 'mobile',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important time in your cursus, during which you learn a new language, or even a new paradigm.`,
    catInferred: false,
  },
  {
    id: 2007,
    name: 'NetPractice',
    slug: 'netpractice',
    xp: 3160,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A hands-on networking project with 10 progressive levels teaching TCP/IP addressing, subnet masks, default gateways, routing, and OSI layers, by troubleshooting and configuring non-functioning network diagrams in the browser.`,
    catInferred: false,
  },
  {
    id: 1635,
    name: 'Open Project',
    slug: 'open-project',
    xp: 31500,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Long-term project management on a topic of your choice, including computer-science-related elements. Collaborate with other 42 students and complete within 6 months.`,
    catInferred: false,
  },
  {
    id: 2706,
    name: 'Pac-Man',
    slug: 'pac-man',
    xp: 7717,
    status: 'Unavailable (locked)' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Recreate the famous arcade game Pac-Man with a modern Python codebase, a clean project structure, and a deployable build.`,
    catInferred: true,
  },
  {
    id: 2552,
    name: 'Peace_Break',
    slug: 'peace-break',
    xp: 9000,
    status: 'Not recommended' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Inspired by the classic game 'Brick Breaker', a great introduction to mobile development: design a user-friendly interface, manage user data, implement core gameplay features.`,
    catInferred: true,
  },
  {
    id: 1334,
    name: 'Philosophers',
    slug: 'philosophers',
    xp: 3360,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project aims to teach concurrent programming, focusing on multithreading and multiprocessing.`,
    catInferred: false,
  },
  {
    id: 2295,
    name: 'Piscine Data Science',
    slug: 'piscine-data-science',
    xp: 0,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Introduction to data science via the different professions.`,
    catInferred: false,
  },
  {
    id: 2189,
    name: 'Piscine Django',
    slug: 'piscine-django',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important time in your cursus, during which you learn a new language, or even a new paradigm.`,
    catInferred: false,
  },
  {
    id: 2364,
    name: 'Piscine Object',
    slug: 'piscine-object',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important time in your cursus, during which you learn a new language, or even a new paradigm.`,
    catInferred: false,
  },
  {
    id: 2228,
    name: 'Piscine ocaml',
    slug: 'piscine-ocaml',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important time in your cursus, during which you learn a new language, or even a new paradigm.`,
    catInferred: false,
  },
  {
    id: 2690,
    name: 'Python Module 00',
    slug: 'python-module-00',
    xp: 70,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Introduction to Python programming through practical community garden scenarios.`,
    catInferred: false,
  },
  {
    id: 2691,
    name: 'Python Module 01',
    slug: 'python-module-01',
    xp: 70,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Learn Object-Oriented Programming by becoming a digital gardener — the best way to understand classes is to grow virtual plants and realize you've been doing OOP all along.`,
    catInferred: false,
  },
  {
    id: 2692,
    name: 'Python Module 02',
    slug: 'python-module-02',
    xp: 80,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Build robust garden data pipelines: master Python exception handling through smart agriculture monitoring — catch sensor failures, create custom plant alerts, keep your digital greenhouse running when things go wrong.`,
    catInferred: false,
  },
  {
    id: 2693,
    name: 'Python Module 03',
    slug: 'python-module-03',
    xp: 80,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master Python's powerful data structures while building and processing game data.`,
    catInferred: false,
  },
  {
    id: 2694,
    name: 'Python Module 04',
    slug: 'python-module-04',
    xp: 90,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Preserve digital knowledge by mastering file operations, managing data streams, and building robust archival systems.`,
    catInferred: false,
  },
  {
    id: 2695,
    name: 'Python Module 05',
    slug: 'python-module-05',
    xp: 90,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master abstract classes, method overriding and subtype polymorphism by building data processing systems.`,
    catInferred: false,
  },
  {
    id: 2696,
    name: 'Python Module 06',
    slug: 'python-module-06',
    xp: 100,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master Python's import system through alchemical experiments, including __init__.py package control, import styles, absolute vs relative imports, and circular dependency resolution.`,
    catInferred: false,
  },
  {
    id: 2697,
    name: 'Python Module 07',
    slug: 'python-module-07',
    xp: 100,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master Python's design patterns with abstract classes and interfaces by building a modular card system.`,
    catInferred: false,
  },
  {
    id: 2698,
    name: 'Python Module 08',
    slug: 'python-module-08',
    xp: 100,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This Matrix-themed project explores essential data engineering tools: virtual environments, package management (pip/Poetry), and environment variables.`,
    catInferred: false,
  },
  {
    id: 2707,
    name: 'Python Module 09',
    slug: 'python-module-09',
    xp: 110,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master Pydantic — Python's data validation library — through space-themed exercises: robust data models, custom validation rules, complex nested structures.`,
    catInferred: false,
  },
  {
    id: 2699,
    name: 'Python Module 10',
    slug: 'python-module-10',
    xp: 110,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Master Python's advanced functional programming through a cyberpunk RPG: higher-order functions, decorators, and lambdas to save the digital realm from chaos.`,
    catInferred: false,
  },
  {
    id: 2267,
    name: 'Python for Data Science',
    slug: 'python-for-data-science',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important time in your cursus, during which you learn a new language, or even a new paradigm.`,
    catInferred: false,
  },
  {
    id: 2744,
    name: 'RAG against the machine',
    slug: 'rag-against-the-machine',
    xp: 7717,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['Call Me Maybe'],
    unlocks: ['Agent smith'],
    isRoot: false,
    topic: `Build a Retrieval-Augmented Generation system that answers questions about codebases by retrieving relevant information and generating evidence-based responses, implementing intelligent chunking and efficient retrieval (TF-IDF/BM25).`,
    catInferred: true,
  },
  {
    id: 2700,
    name: 'RAG against the machine',
    slug: 'rag-against-the-machine-2',
    xp: 7717,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Build a Retrieval-Augmented Generation system that answers questions about codebases by retrieving relevant information and generating evidence-based responses, implementing intelligent chunking and efficient retrieval (TF-IDF/BM25).`,
    catInferred: true,
  },
  {
    id: 2749,
    name: 'RetroEmu',
    slug: 'retroemu',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['lem-ipc'],
    unlocks: [''],
    isRoot: false,
    topic: `This project involves coding an emulator for an 8-bit handheld console (DMG model) and its color variant (CGB model) — technical documentation, hardware emulation, and ROM cartridges.`,
    catInferred: true,
  },
  {
    id: 2350,
    name: 'Spring Boot',
    slug: 'spring-boot',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['cinema'],
    unlocks: ['restful'],
    isRoot: false,
    topic: `Make a final MVP for your web application using the current Java-based Spring Boot development technology.`,
    catInferred: true,
  },
  {
    id: 1662,
    name: 'Startup Experience',
    slug: 'startup-experience',
    xp: 63000,
    status: 'Available' as Status,
    categories: ['Professional Experience'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Successful professional integration remains a fundamental school objective. This project lets you found a startup and work on it full-time for at least six months.`,
    catInferred: false,
  },
  {
    id: 2748,
    name: 'Supercharge',
    slug: 'supercharge',
    xp: 0,
    status: 'Unavailable (locked)' as Status,
    categories: ['Cryptography & Maths'],
    requires: ['Ftl_quantum'],
    unlocks: [''],
    isRoot: false,
    topic: `Go from a quantum algorithm to a real optimization problem. Build a web app that places electric vehicle charging stations on a real map, comparing a classical brute-force solver against a quantum QAOA solver.`,
    catInferred: true,
  },
  {
    id: 2701,
    name: 'The Answer Protocol',
    slug: 'the-answer-protocol',
    xp: 15836,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create a multiplayer text adventure that unites learners in a shared virtual world with dynamic item management. Working in pairs, build a robust TCP server implementing a custom protocol (RFC 42TAP) using systems languages (C, C++, Rust, Go, or Zig — Python is forbidden), with CLI and graphical clients, chat, presence events, group coordination, and a sophisticated item economy.`,
    catInferred: true,
  },
  {
    id: 2719,
    name: 'TokenZwap',
    slug: 'tokenzwap',
    xp: 9000,
    status: 'Not recommended' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project introduces you to the fundamentals of decentralized finance (DeFi). You will build an Automated Market Maker (AMM) where users can swap tokens and buy/sell NFTs!`,
    catInferred: true,
  },
  {
    id: 2600,
    name: 'TokenizeArt',
    slug: 'tokenizeart',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project allows you to learn the basics in web3: create your non-fungible token.`,
    catInferred: true,
  },
  {
    id: 2485,
    name: 'Tokenizer',
    slug: 'tokenizer',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project allows you to learn the basics in web3. You will have to create your personal token!`,
    catInferred: true,
  },
  {
    id: 1955,
    name: 'Uber',
    slug: 'uber',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?5268'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to time series analysis: stationarity, exponential smoothing, SARIMA.`,
    catInferred: true,
  },
  {
    id: 1956,
    name: 'Understanding customer',
    slug: 'understanding-customer',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?5235'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to deep learning and NLP: recurrent neural nets (RNN), LSTM, Transformer, BERT.`,
    catInferred: true,
  },
  {
    id: 2288,
    name: 'Unity',
    slug: 'unity',
    xp: 0,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Piscines are an important part of your curriculum, giving you the opportunity to learn a new language — or explore a completely new paradigm.`,
    catInferred: false,
  },
  {
    id: 2393,
    name: 'UnleashTheBox',
    slug: 'unleashthebox',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Security'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `An immersive cybersecurity project where you learn to exploit systems and acquire essential info-sec skills.`,
    catInferred: true,
  },
  {
    id: 2553,
    name: 'Very_Real_Engine',
    slug: 'very-real-engine',
    xp: 30000,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create and implement a library containing all necessary tools, notably a graphics engine and a physics engine.`,
    catInferred: true,
  },
  {
    id: 1638,
    name: 'Work Experience I',
    slug: 'work-experience-i',
    xp: 42000,
    status: 'Done' as Status,
    categories: ['Professional Experience'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Your first step in a company: an important milestone in your 42 training. Designed to help you discover the professional world and apply your work ethic and adaptability in a real-world context — a first asset for your resume.`,
    catInferred: false,
  },
  {
    id: 1644,
    name: 'Work Experience II',
    slug: 'work-experience-ii',
    xp: 63000,
    status: 'Unavailable (locked)' as Status,
    categories: ['Professional Experience'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Your course can continue with a second period of professional integration: the second internship. The accomplishment of your journey, demonstrating your expertise professionally in a company — the springboard for your career.`,
    catInferred: false,
  },
  {
    id: 1461,
    name: 'abstract-vm',
    slug: 'abstract-vm',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: ['libftpp'],
    unlocks: [''],
    isRoot: false,
    topic: `Back into the flow after the C++ piscine: create a virtual machine capable of executing code in basic pseudo-ASM, using a stack for arithmetic operations, similar to the dc command.`,
    catInferred: true,
  },
  {
    id: 1435,
    name: 'avaj-launcher',
    slug: 'avaj-launcher',
    xp: 4200,
    status: 'Unavailable (locked)' as Status,
    categories: ['Development'],
    requires: ['Java Module 09'],
    unlocks: ['swingy'],
    isRoot: false,
    topic: `First project of the Java arc: implementation of a simple Java program according to a given class diagram written in UML.`,
    catInferred: false,
  },
  {
    id: 1389,
    name: 'bomberman',
    slug: 'bomberman',
    xp: 25200,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['humangl'],
    unlocks: [''],
    isRoot: false,
    topic: `Recode Bomberman, a classic game, in C++ and OpenGL — your first major professional-grade C++ project, aiming for the most polished game possible.`,
    catInferred: false,
  },
  {
    id: 1446,
    name: 'boot2root',
    slug: 'boot2root',
    xp: 11500,
    status: 'Unavailable (locked)' as Status,
    categories: ['Security'],
    requires: ['snow-crash'],
    unlocks: [''],
    isRoot: false,
    topic: `This project introduces computer security through a hands-on challenge: you are given access to a deliberately vulnerable Linux server and must become root by at least two distinct methods, via reconnaissance, web exploitation, and privilege escalation chains, documented in a writeup.`,
    catInferred: false,
  },
  {
    id: 1396,
    name: 'camagru',
    slug: 'camagru',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project is a warm-up for web development. You will need to create a small, Instagram-like website that allows users to create and share photomontages. From scratch, you will implement the basic functionalities commonly used by any website with a user base.`,
    catInferred: false,
  },
  {
    id: 2625,
    name: 'cc1',
    slug: 'cc1',
    xp: 50000,
    status: 'Not recommended' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project is about creating a C compiler.`,
    catInferred: true,
  },
  {
    id: 1934,
    name: 'churn',
    slug: 'churn',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?5222'],
    unlocks: [''],
    isRoot: false,
    topic: `This project is an introduction to artificial neural nets: fully-connected neural nets, hidden layers, activation functions, back-propagation, dropout.`,
    catInferred: true,
  },
  {
    id: 2349,
    name: 'cinema',
    slug: 'cinema',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['fwa'],
    unlocks: ['Spring Boot'],
    isRoot: false,
    topic: `Expand your knowledge of Java web development using the Spring stack and master the Hibernate framework.`,
    catInferred: true,
  },
  {
    id: 1414,
    name: 'cloud-1',
    slug: 'cloud-1',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Devops'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project is an introduction to cloud servers.`,
    catInferred: false,
  },
  {
    id: 1382,
    name: 'computorv1',
    slug: 'computorv1',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Cryptography & Maths'],
    requires: [''],
    unlocks: ['computorv2'],
    isRoot: true,
    topic: `Get acquainted with handling elementary math tools helpful for other 42 projects, via a progressive, relaxed approach. You can choose the language.`,
    catInferred: false,
  },
  {
    id: 1433,
    name: 'computorv2',
    slug: 'computorv2',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Cryptography & Maths'],
    requires: ['computorv1'],
    unlocks: [''],
    isRoot: false,
    topic: `Now that you've programmed your equation solver, go further: create your own calculator from the command line, integrating Computor V1 plus matrix calculus, function solving, and complex numbers.`,
    catInferred: false,
  },
  {
    id: 1475,
    name: 'corewar',
    slug: 'corewar',
    xp: 17500,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data", "Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create a virtual arena where simplistic-language programs fight each other: VM conception (instructions, registers) and compiling an assembly language into bytecode. Bonus: watch your champions fight.`,
    catInferred: false,
  },
  {
    id: 1326,
    name: 'cub3d',
    slug: 'cub3d',
    xp: 5775,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Inspired by the world-famous 90's game that was the first FPS ever. Explore ray-casting: make a dynamic view inside a maze, in which you find your way.`,
    catInferred: false,
  },
  {
    id: 1405,
    name: 'darkly',
    slug: 'darkly',
    xp: 6300,
    status: 'Available' as Status,
    categories: ['Security", "Web & Mobile'],
    requires: ['?1482'],
    unlocks: [''],
    isRoot: false,
    topic: `Introductory project to computer security in the specific field of the web: audit a deliberately vulnerable web platform, exploiting real-world vulnerabilities to escalate access from anonymous visitor to administrator, capturing flags and understanding how each breach could have been prevented.`,
    catInferred: false,
  },
  {
    id: 1445,
    name: 'death',
    slug: 'death',
    xp: 35700,
    status: 'Unavailable (locked)' as Status,
    categories: ['Security'],
    requires: ['war'],
    unlocks: [''],
    isRoot: false,
    topic: `Last virus project: combine your Famine, Pestilence and War into real metamorphic code.`,
    catInferred: false,
  },
  {
    id: 1458,
    name: 'doom-nukem',
    slug: 'doom-nukem',
    xp: 15750,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Pushes raycasting possibilities further with a dimension of game design — a mix of Doom and Duke Nukem 3D, plus features of your own.`,
    catInferred: false,
  },
  {
    id: 1418,
    name: 'dr-quine',
    slug: 'dr-quine',
    xp: 2520,
    status: 'Available' as Status,
    categories: ['Security'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A small algo project that gets you acquainted with auto-replication problems and the Kleene recursion theorem.`,
    catInferred: false,
  },
  {
    id: 1422,
    name: 'drivers-and-interrupts',
    slug: 'drivers-and-interrupts',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: ['little-penguin-1'],
    unlocks: ['filesystem'],
    isRoot: false,
    topic: `Learn how to connect a driver to your kernel, using a keyboard driver.`,
    catInferred: false,
  },
  {
    id: 1453,
    name: 'dslr',
    slug: 'dslr',
    xp: 6000,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: ['multilayer-perceptron", "total-perspective-vortex'],
    isRoot: true,
    topic: `Discover Data Science by recreating the Hogwarts Sorting Hat using logistic regression.`,
    catInferred: false,
  },
  {
    id: 1384,
    name: 'expert-system',
    slug: 'expert-system',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['n-puzzle'],
    unlocks: [''],
    isRoot: false,
    topic: `Create, in the language of your choice, an expert system in propositional calculus: a program that reasons on rules and initial facts to deduce other facts.`,
    catInferred: false,
  },
  {
    id: 1430,
    name: 'famine',
    slug: 'famine',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Security'],
    requires: ['woody-woodpacker'],
    unlocks: ['pestilence'],
    isRoot: false,
    topic: `The world of viruses, trojans and other malware: put your binary-file skills to work and make your first virus (educational purposes only).`,
    catInferred: false,
  },
  {
    id: 1423,
    name: 'filesystem',
    slug: 'filesystem',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: ['drivers-and-interrupts", "process-and-memory'],
    unlocks: [''],
    isRoot: false,
    topic: `Create your own filesystem, for your linux kernel.`,
    catInferred: false,
  },
  {
    id: 1437,
    name: 'fix-me',
    slug: 'fix-me',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['Development'],
    requires: ['swingy'],
    unlocks: [''],
    isRoot: false,
    topic: `Final project of the Java arc: write a program simulating stock exchanges and handling trading algorithms, including networking and socket implementations.`,
    catInferred: false,
  },
  {
    id: 1476,
    name: 'fract-ol',
    slug: 'fract-ol',
    xp: 1000,
    status: 'Unavailable (locked)' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Discover 2D programming and the psychedelic universe of fractals, using minilibX.`,
    catInferred: true,
  },
  {
    id: 1883,
    name: 'freddie-mercury',
    slug: 'freddie-mercury',
    xp: 12600,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['xv'],
    unlocks: [''],
    isRoot: false,
    topic: `VR escape game.`,
    catInferred: true,
  },
  {
    id: 1407,
    name: 'ft_ality',
    slug: 'ft-ality',
    xp: 4200,
    status: 'Not recommended' as Status,
    categories: ['Development'],
    requires: ['ft_turing'],
    unlocks: [''],
    isRoot: false,
    topic: `This project will get you acquainted with problems linked to automatic syntax analysis (parsing) by studying finite automation in a combat game.`,
    catInferred: false,
  },
  {
    id: 1379,
    name: 'ft_hangouts',
    slug: 'ft-hangouts',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `An introduction to mobile app development: build a contact management app for Android, learning how apps work, lifecycle management, and the Android SDK.`,
    catInferred: false,
  },
  {
    id: 1336,
    name: 'ft_irc',
    slug: 'ft-irc',
    xp: 21630,
    status: 'Unavailable (locked)' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create your own IRC server in C++98, compatible with a standard IRC client for the required features.`,
    catInferred: true,
  },
  {
    id: 2098,
    name: 'ft_kalman',
    slug: 'ft-kalman',
    xp: 16800,
    status: 'Not recommended' as Status,
    categories: ['Cryptography & Maths'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Aboard a generic vehicle with flawed sensors, create a kalman filter to track its position coordinates. A good introduction to signal filtering, matrix operations, gaussian noise and correlation.`,
    catInferred: false,
  },
  {
    id: 2380,
    name: 'ft_lex',
    slug: 'ft-lex',
    xp: 15000,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A project about lexical analysis and finite automata, implementing a powerful regex engine.`,
    catInferred: false,
  },
  {
    id: 2747,
    name: 'ft_lgtm',
    slug: 'ft-lgtm',
    xp: 0,
    status: 'Not recommended' as Status,
    categories: ['Devops'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Build a web application that runs untrusted code securely with WASM/WASI, uploads it to IPFS, and monitors everything with a complete LGTM observability stack on Kubernetes.`,
    catInferred: true,
  },
  {
    id: 1391,
    name: 'ft_linear_regression',
    slug: 'ft-linear-regression',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data", "Cryptography & Maths'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Your first steps into AI and Machine Learning: a simple basic ML algorithm — predict the price of a car using a linear function trained with gradient descent.`,
    catInferred: false,
  },
  {
    id: 1415,
    name: 'ft_linux',
    slug: 'ft-linux',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: ['little-penguin-1'],
    isRoot: true,
    topic: `The first project of the Kernel branch: build your own Linux-From-Scratch distribution, used in the next projects.`,
    catInferred: false,
  },
  {
    id: 1479,
    name: 'ft_ls',
    slug: 'ft-ls',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `For knowing the filesystem inside out, and how files and directories are sorted, code by yourself one of the most used commands: ls.`,
    catInferred: false,
  },
  {
    id: 2394,
    name: 'ft_microservices',
    slug: 'ft-microservices',
    xp: 4200,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['restful'],
    unlocks: ['Microshop", "messagequeue'],
    isRoot: false,
    topic: `Master the skills of creating microservice applications using the Spring framework.`,
    catInferred: true,
  },
  {
    id: 2126,
    name: 'ft_minecraft',
    slug: 'ft-minecraft',
    xp: 20750,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['ft_vox'],
    unlocks: [''],
    isRoot: false,
    topic: `The continuation of ft_vox, with a more advanced approach to procedural generation, rendering techniques and networking.`,
    catInferred: false,
  },
  {
    id: 1962,
    name: 'ft_newton',
    slug: 'ft-newton',
    xp: 24360,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['humangl'],
    unlocks: [''],
    isRoot: false,
    topic: `Basic physics engine: motion, gravity, collisions.`,
    catInferred: false,
  },
  {
    id: 1400,
    name: 'ft_nmap',
    slug: 'ft-nmap',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Security", "Devops", "System & Kernel'],
    requires: ['ft_traceroute'],
    unlocks: [''],
    isRoot: false,
    topic: `Re-coding the nmap command deepens your knowledge of TCP/IP networks and advanced use of threads in real life.`,
    catInferred: false,
  },
  {
    id: 1397,
    name: 'ft_ping',
    slug: 'ft-ping',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Devops", "System & Kernel'],
    requires: [''],
    unlocks: ['ft_ssl_md5", "ft_traceroute'],
    isRoot: true,
    topic: `Re-coding the ping command familiarizes you with raw IP communication between two machines on a network.`,
    catInferred: false,
  },
  {
    id: 1316,
    name: 'ft_printf',
    slug: 'ft-printf',
    xp: 882,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Recode printf. You will learn what and how to implement variadic functions, then reuse this function in your future projects.`,
    catInferred: false,
  },
  {
    id: 1466,
    name: 'ft_script',
    slug: 'ft-script',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `By re-coding the script command you will understand interactions between user input and tty, notably line discipline as well as pseudo-terminals — and why Ctrl-C interrupts a running program.`,
    catInferred: true,
  },
  {
    id: 1469,
    name: 'ft_select',
    slug: 'ft-select',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Get started on terminal manipulation with termcaps: create a user interface for a program launched on the terminal.`,
    catInferred: true,
  },
  {
    id: 1447,
    name: 'ft_shield',
    slug: 'ft-shield',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Security'],
    requires: ['woody-woodpacker'],
    unlocks: [''],
    isRoot: false,
    topic: `Use your skills to create a daemon — your first basic trojan.`,
    catInferred: false,
  },
  {
    id: 1452,
    name: 'ft_ssl_des',
    slug: 'ft-ssl-des',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Cryptography & Maths'],
    requires: ['ft_ssl_md5'],
    unlocks: ['ft_ssl_rsa'],
    isRoot: false,
    topic: `You will reimplement part of the OpenSSL program, specifically BASE64, DES-ECB, and DES-CBC.`,
    catInferred: false,
  },
  {
    id: 1451,
    name: 'ft_ssl_md5',
    slug: 'ft-ssl-md5',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Cryptography & Maths'],
    requires: ['ft_ping'],
    unlocks: ['ft_ssl_des'],
    isRoot: false,
    topic: `You will recode part of the OpenSSL program, specifically the MD5 Hashing Algorithm.`,
    catInferred: false,
  },
  {
    id: 1450,
    name: 'ft_ssl_rsa',
    slug: 'ft-ssl-rsa',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Cryptography & Maths'],
    requires: ['ft_ssl_des'],
    unlocks: [''],
    isRoot: false,
    topic: `Code your own random prime number generator and use it to make private RSA keys.`,
    catInferred: false,
  },
  {
    id: 1399,
    name: 'ft_traceroute',
    slug: 'ft-traceroute',
    xp: 4200,
    status: 'Not recommended' as Status,
    categories: ['Devops", "System & Kernel'],
    requires: ['ft_ping'],
    unlocks: ['ft_nmap'],
    isRoot: false,
    topic: `Re-coding the traceroute command deepens your knowledge of TCP/IP networks by following the paths of an IP packet from one machine to another.`,
    catInferred: false,
  },
  {
    id: 1337,
    name: 'ft_transcendence',
    slug: 'ft-transcendence',
    xp: 24360,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Design, develop, and organize a full-stack web application with complete creative freedom: choose your concept, pick from technical modules, make key architectural decisions.`,
    catInferred: false,
  },
  {
    id: 1403,
    name: 'ft_turing',
    slug: 'ft-turing',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: ['ft_ality", "h42n42'],
    isRoot: true,
    topic: `Discover the Turing model using imperative programming, implementing the model with OCaml.`,
    catInferred: false,
  },
  {
    id: 1449,
    name: 'ft_vox',
    slug: 'ft-vox',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['scop'],
    unlocks: ['ft_minecraft'],
    isRoot: false,
    topic: `Introduces voxel engines, inspired by Minecraft, where you must create a randomly generated world.`,
    catInferred: false,
  },
  {
    id: 2381,
    name: 'ft_yacc',
    slug: 'ft-yacc',
    xp: 20000,
    status: 'Not recommended' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A project about syntactic analysis and stack automata.`,
    catInferred: false,
  },
  {
    id: 2347,
    name: 'fwa',
    slug: 'fwa',
    xp: 4200,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['Java Module 09'],
    unlocks: ['cinema'],
    isRoot: false,
    topic: `Develop your First Web Application using standard Java technologies.`,
    catInferred: true,
  },
  {
    id: 1327,
    name: 'get_next_line',
    slug: 'get-next-line',
    xp: 882,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Whether it's a file, stdin, or later a network connection, you'll always need a way to read content line by line. Essential for your future projects.`,
    catInferred: false,
  },
  {
    id: 1383,
    name: 'gomoku',
    slug: 'gomoku',
    xp: 25200,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['n-puzzle'],
    unlocks: [''],
    isRoot: false,
    topic: `Create, in the language of your choice, a Gomoku game with an AI player capable of beating a human as fast as possible, implementing a min-max algorithm and researching the most adapted heuristics.`,
    catInferred: false,
  },
  {
    id: 1455,
    name: 'guimp',
    slug: 'guimp',
    xp: 12600,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create a graphic interface library, proven with a small 2D image editing app. As complete and modular as possible, reusable in future graphics/other projects.`,
    catInferred: false,
  },
  {
    id: 1429,
    name: 'h42n42',
    slug: 'h42n42',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Development'],
    requires: ['ft_turing'],
    unlocks: [''],
    isRoot: false,
    topic: `An introductory project to the OCSIGEN framework for creating rich web applications in OCaml. The goal is to design a simulator where creatures try to escape a dangerous virus.`,
    catInferred: false,
  },
  {
    id: 1394,
    name: 'humangl',
    slug: 'humangl',
    xp: 4200,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['scop'],
    unlocks: ['bomberman", "ft_newton", "particle-system", "shaderpixel'],
    isRoot: false,
    topic: `This intermediate OpenGL project is an introduction to hierarchical modeling: use matrices to link various parts of a humanoid model, and animate them.`,
    catInferred: false,
  },
  {
    id: 1402,
    name: 'hypertube',
    slug: 'hypertube',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Web & Mobile'],
    requires: ['matcha'],
    unlocks: [''],
    isRoot: false,
    topic: `Introduces MVC frameworks: build a video streaming website with content downloaded via the BitTorrent protocol, using an MVC framework in the language of your choice.`,
    catInferred: false,
  },
  {
    id: 1409,
    name: 'in-the-shadows',
    slug: 'in-the-shadows',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: ['xv'],
    isRoot: true,
    topic: `Develop a complete game using a bit of algo and a lot of creativity.`,
    catInferred: false,
  },
  {
    id: 1425,
    name: 'kfs-1',
    slug: 'kfs-1',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['little-penguin-1'],
    unlocks: ['kfs-2'],
    isRoot: false,
    topic: `Discover the world of Kernel Programming and learn how to create your very own Kernel from scratch.`,
    catInferred: false,
  },
  {
    id: 1424,
    name: 'kfs-2',
    slug: 'kfs-2',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-1'],
    unlocks: ['kfs-3'],
    isRoot: false,
    topic: `Discover the world of Kernel Programming and learn how to create your very own Kernel from scratch.`,
    catInferred: false,
  },
  {
    id: 1426,
    name: 'kfs-3',
    slug: 'kfs-3',
    xp: 35700,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-2'],
    unlocks: ['kfs-4'],
    isRoot: false,
    topic: `Third Kernel-from-Scratch project: learn how to manage memory in your kernel.`,
    catInferred: false,
  },
  {
    id: 1431,
    name: 'kfs-4',
    slug: 'kfs-4',
    xp: 25200,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-3'],
    unlocks: ['kfs-5'],
    isRoot: false,
    topic: `Create an Interrupt Description Table and handle interrupts within your Kernel.`,
    catInferred: false,
  },
  {
    id: 1432,
    name: 'kfs-5',
    slug: 'kfs-5',
    xp: 35700,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-4'],
    unlocks: ['kfs-6'],
    isRoot: false,
    topic: `Develop process managing in your Kernel, by implementing how to interpret the fork-bomb command :(){ :|:& }.`,
    catInferred: false,
  },
  {
    id: 1438,
    name: 'kfs-6',
    slug: 'kfs-6',
    xp: 25200,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-5'],
    unlocks: ['kfs-7'],
    isRoot: false,
    topic: `Keep developing your own kernel: set up your own filesystem.`,
    catInferred: false,
  },
  {
    id: 1439,
    name: 'kfs-7',
    slug: 'kfs-7',
    xp: 35700,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-6'],
    unlocks: ['kfs-8'],
    isRoot: false,
    topic: `This project will teach you how to build your own syscalls for your kernel, as well as user accounts, sockets, and a Unix-like hierarchy. Almost a full kernel.`,
    catInferred: false,
  },
  {
    id: 1440,
    name: 'kfs-8',
    slug: 'kfs-8',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-7'],
    unlocks: ['kfs-9'],
    isRoot: false,
    topic: `Build a module interface for your kernel.`,
    catInferred: false,
  },
  {
    id: 1441,
    name: 'kfs-9',
    slug: 'kfs-9',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-8'],
    unlocks: ['kfs-x'],
    isRoot: false,
    topic: `Create an ELF parser and loader for your kernel.`,
    catInferred: false,
  },
  {
    id: 1442,
    name: 'kfs-x',
    slug: 'kfs-x',
    xp: 35700,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['kfs-9'],
    unlocks: [''],
    isRoot: false,
    topic: `The final kernel project: create a complete linux environment. Maybe name your kernel too.`,
    catInferred: false,
  },
  {
    id: 1392,
    name: 'krpsim',
    slug: 'krpsim',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['n-puzzle'],
    unlocks: [''],
    isRoot: false,
    topic: `Create a program that optimizes rendering of a process graph under resource constraints. Explore existing algorithms and choose/create what fits; choose your language.`,
    catInferred: false,
  },
  {
    id: 1464,
    name: 'lem-ipc',
    slug: 'lem-ipc',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: ['malloc'],
    unlocks: ['RetroEmu", "nibbler", "strace'],
    isRoot: false,
    topic: `Explore Unix tools that enable processes to communicate locally (as opposed to over a network via TCP/IP). Practice these concepts by building a client for a classic board game.`,
    catInferred: false,
  },
  {
    id: 1470,
    name: 'lem_in',
    slug: 'lem-in',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Your ant colony must move from one point to another in the shortest time possible. Get acquainted with graph traversal algorithms: intelligently select paths and precise movements for the ants.`,
    catInferred: false,
  },
  {
    id: 1330,
    name: 'libasm',
    slug: 'libasm',
    xp: 966,
    status: 'Available' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `The aim of this project is to become familiar with assembly language.`,
    catInferred: false,
  },
  {
    id: 2550,
    name: 'libftpp',
    slug: 'libftpp',
    xp: 5880,
    status: 'Available' as Status,
    categories: ['Development'],
    requires: [''],
    unlocks: ['abstract-vm'],
    isRoot: true,
    topic: `This subject introduces advanced C++ concepts through the development of complex tools and systems.`,
    catInferred: true,
  },
  {
    id: 1416,
    name: 'little-penguin-1',
    slug: 'little-penguin-1',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: ['ft_linux'],
    unlocks: ['drivers-and-interrupts", "kfs-1", "process-and-memory", "userspace_digressions'],
    isRoot: false,
    topic: `The start of a series of challenges inspired by Eudyptula. You will get acquainted with many points of Kernel development.`,
    catInferred: false,
  },
  {
    id: 1468,
    name: 'malloc',
    slug: 'malloc',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: ['lem-ipc'],
    isRoot: true,
    topic: `What's the deal with malloc? You've used it since the piscine but it's not a syscall. Find out the workings behind optimum memory management and recode it, as well as free and realloc.`,
    catInferred: false,
  },
  {
    id: 1401,
    name: 'matcha',
    slug: 'matcha',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: ['hypertube'],
    isRoot: true,
    topic: `A more advanced tool for building web apps — the micro-framework. Create a dating site in the language of your choice; user interaction is at the heart of this project.`,
    catInferred: false,
  },
  {
    id: 2077,
    name: 'matrix',
    slug: 'matrix',
    xp: 7000,
    status: 'Available' as Status,
    categories: ['Cryptography & Maths'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Formalize vectors and vector spaces through Linear Algebra and learn how matrices and linear transformations work.`,
    catInferred: false,
  },
  {
    id: 1420,
    name: 'matt-daemon',
    slug: 'matt-daemon',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['taskmaster'],
    unlocks: [''],
    isRoot: false,
    topic: `A Unix project to create a server-type daemon. This server will listen on a given port and interpret a list of commands.`,
    catInferred: false,
  },
  {
    id: 2353,
    name: 'messagequeue',
    slug: 'messagequeue',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['ft_microservices'],
    unlocks: [''],
    isRoot: false,
    topic: `Learn how to work with a large flow of tasks using RabbitMQ, a popular implementation of the message-queue pattern.`,
    catInferred: true,
  },
  {
    id: 1315,
    name: 'miniRT',
    slug: 'minirt',
    xp: 5775,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project is an introduction to the beautiful world of Raytracing.`,
    catInferred: false,
  },
  {
    id: 1331,
    name: 'minishell',
    slug: 'minishell',
    xp: 2814,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `The objective of this project is for you to create a simple shell.`,
    catInferred: false,
  },
  {
    id: 2005,
    name: 'minitalk',
    slug: 'minitalk',
    xp: 1142,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Code a small data exchange program using UNIX signals. An introductory project for the bigger UNIX projects later in the cursus.`,
    catInferred: false,
  },
  {
    id: 1462,
    name: 'mod1',
    slug: 'mod1',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A simulation graphic project representing a surface in 3D, on which water flows. Empirical or scientific: recreate a wave, tsunami, or rain on your surface.`,
    catInferred: false,
  },
  {
    id: 1457,
    name: 'multilayer-perceptron',
    slug: 'multilayer-perceptron',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['dslr'],
    unlocks: [''],
    isRoot: false,
    topic: `This project is an introduction to artificial neural networks through the implementation of a multilayer perceptron.`,
    catInferred: false,
  },
  {
    id: 1427,
    name: 'music-room',
    slug: 'music-room',
    xp: 25200,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `In a group, create a complete mobile app for collaborative playlists using a relevant SDK/API: mobile dev, back-end dev, and a REST API.`,
    catInferred: false,
  },
  {
    id: 1943,
    name: 'mySpotify',
    slug: 'myspotify',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?5223'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to recommendation algorithms: non-personalized, content-based, collaborative filtering.`,
    catInferred: true,
  },
  {
    id: 1385,
    name: 'n-puzzle',
    slug: 'n-puzzle',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: ['expert-system", "gomoku", "krpsim'],
    isRoot: true,
    topic: `Create, in any language, a program capable of solving N-puzzles of various sizes as efficiently as possible.`,
    catInferred: false,
  },
  {
    id: 1386,
    name: 'nibbler',
    slug: 'nibbler',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel", "Graphics & Gaming'],
    requires: ['lem-ipc'],
    unlocks: [''],
    isRoot: false,
    topic: `This project in C++ will make you recode a Snake where you can switch the interface at run time.`,
    catInferred: false,
  },
  {
    id: 1467,
    name: 'nm',
    slug: 'nm',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: ['woody-woodpacker'],
    isRoot: true,
    topic: `This project will educate you on a deeper comprehension of how linux handles executables, by re-creating the command nm.`,
    catInferred: false,
  },
  {
    id: 1448,
    name: 'override',
    slug: 'override',
    xp: 35700,
    status: 'Unavailable (locked)' as Status,
    categories: ['Security'],
    requires: ['rainfall'],
    unlocks: [''],
    isRoot: false,
    topic: `Override is the direct sequel to Rainfall, and it is another level entirely. Rainfall taught you the stack; Override drops you into modern, fully mitigated 64-bit binaries on glibc 2.39, all protections on by default. Stripped binaries, no shortcuts, the heap and the network in play. Serious binary exploitation.`,
    catInferred: false,
  },
  {
    id: 1410,
    name: 'particle-system',
    slug: 'particle-system',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['humangl'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to GPU programming: design a particle system meeting performance constraints, using GPU libraries (OpenGL, OpenCL, Metal, CUDA, Vulkan, WebGPU...) to parallelize computations.`,
    catInferred: false,
  },
  {
    id: 1443,
    name: 'pestilence',
    slug: 'pestilence',
    xp: 15750,
    status: 'Unavailable (locked)' as Status,
    categories: ['Security'],
    requires: ['famine'],
    unlocks: ['war'],
    isRoot: false,
    topic: `Second virus project: reuse the Famine base to add a method of hiding your code.`,
    catInferred: false,
  },
  {
    id: 2004,
    name: 'pipex',
    slug: 'pipex',
    xp: 1142,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project deepens your understanding of Redirections and Pipes. An introductory project for the bigger UNIX projects later in the cursus.`,
    catInferred: false,
  },
  {
    id: 1421,
    name: 'process-and-memory',
    slug: 'process-and-memory',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: ['little-penguin-1'],
    unlocks: ['filesystem'],
    isRoot: false,
    topic: `An introduction to syscalls and memory management within the linux kernel.`,
    catInferred: false,
  },
  {
    id: 1471,
    name: 'push_swap',
    slug: 'push-swap',
    xp: 1855,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Sort data on a stack, with a limited instruction set, using the smallest number of moves: manipulate sorting algorithms and choose the most appropriate for optimized data sorting.`,
    catInferred: false,
  },
  {
    id: 2687,
    name: 'push_swap',
    slug: 'push-swap-2',
    xp: 1855,
    status: 'Unavailable (locked)' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Sort data on a stack, with a limited instruction set, using the smallest number of moves: manipulate sorting algorithms and choose the most appropriate for optimized data sorting.`,
    catInferred: false,
  },
  {
    id: 1417,
    name: 'rainfall',
    slug: 'rainfall',
    xp: 25200,
    status: 'Unavailable (locked)' as Status,
    categories: ['Security'],
    requires: ['snow-crash'],
    unlocks: ['override'],
    isRoot: false,
    topic: `Rainfall picks up where Snow Crash left off and goes deeper. On a deliberately vulnerable VM, you climb from one account to the next by exploiting a series of SUID ELF binaries: reading their code, mapping memory layout, turning flaws into control of execution. Each level tightens protections (NX, stack canaries, ASLR); Full RELRO and PIE await in the bonus part.`,
    catInferred: false,
  },
  {
    id: 2076,
    name: 'ready set boole',
    slug: 'ready-set-boole',
    xp: 7000,
    status: 'Available' as Status,
    categories: ['Cryptography & Maths'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Discover the basics of computer-related mathematics with Boolean Algebra and Sets Theory.`,
    catInferred: false,
  },
  {
    id: 1428,
    name: 'red-tetris',
    slug: 'red-tetris',
    xp: 15750,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Develop a networked multiplayer Tetris game using an exclusively Full Stack JavaScript stack.`,
    catInferred: false,
  },
  {
    id: 2351,
    name: 'restful',
    slug: 'restful',
    xp: 4200,
    status: 'Unavailable (locked)' as Status,
    categories: ['Web & Mobile'],
    requires: ['Spring Boot'],
    unlocks: ['ft_microservices'],
    isRoot: false,
    topic: `Learn how to use Spring mechanisms to develop REST applications.`,
    catInferred: true,
  },
  {
    id: 1855,
    name: 'rt',
    slug: 'rt',
    xp: 20750,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming", "Cryptography & Maths'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `RT pushes the limits of what Ray Tracing can do: mirror effect, transparency, object cutting, texture application. Build an infrastructure capable of supporting all these ramifications and obtain sublime computer-generated images.`,
    catInferred: false,
  },
  {
    id: 1393,
    name: 'rubik',
    slug: 'rubik',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A non-trivial algorithm project: create a Rubik's cube solver. Choose your language.`,
    catInferred: false,
  },
  {
    id: 1390,
    name: 'scop',
    slug: 'scop',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Graphics & Gaming'],
    requires: [''],
    unlocks: ['42run", "ft_vox", "humangl'],
    isRoot: true,
    topic: `Your introduction to 3D rendering on the GPU using OpenGL, Vulkan, or Metal: explore the core concepts of modern 3D graphics.`,
    catInferred: false,
  },
  {
    id: 1454,
    name: 'shaderpixel',
    slug: 'shaderpixel',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['humangl'],
    unlocks: [''],
    isRoot: false,
    topic: `Now familiar with 3D objects and basic rendering, work in the space of the graphic card: design and create objects using shader programming.`,
    catInferred: false,
  },
  {
    id: 1404,
    name: 'snow-crash',
    slug: 'snow-crash',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Security'],
    requires: [''],
    unlocks: ['boot2root", "rainfall'],
    isRoot: true,
    topic: `Eleven independent security challenges on a deliberately vulnerable Linux VM. Each level requires a distinct technique: binary analysis, process/filesystem inspection, code injection via config files and templates, protocol reverse engineering, jail escapes, and side-channel attacks.`,
    catInferred: false,
  },
  {
    id: 2009,
    name: 'so_long',
    slug: 'so-long',
    xp: 1000,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `A small 2D game with minilibx: learn about textures, sprites and tiles.`,
    catInferred: false,
  },
  {
    id: 1388,
    name: 'strace',
    slug: 'strace',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: ['lem-ipc'],
    unlocks: [''],
    isRoot: false,
    topic: `First step in a series of projects in C leading to creation of a mini-GDB: recode strace, a tool that lists syscalls done by a running program.`,
    catInferred: false,
  },
  {
    id: 1395,
    name: 'swifty-companion',
    slug: 'swifty-companion',
    xp: 4200,
    status: 'Available' as Status,
    categories: ['Web & Mobile'],
    requires: [''],
    unlocks: ['swifty-proteins'],
    isRoot: true,
    topic: `An introduction to mobile programming: create an app to get info about 42 students, using the API.`,
    catInferred: false,
  },
  {
    id: 1406,
    name: 'swifty-proteins',
    slug: 'swifty-proteins',
    xp: 15750,
    status: 'Not recommended' as Status,
    categories: ['Web & Mobile'],
    requires: ['swifty-companion'],
    unlocks: [''],
    isRoot: false,
    topic: `Build a professional mobile app for visualizing protein ligands in 3D: fetch molecular data from the RCSB Protein Data Bank, parse .cif files, render 3D molecular structures natively, with biometric auth and gesture controls.`,
    catInferred: false,
  },
  {
    id: 1436,
    name: 'swingy',
    slug: 'swingy',
    xp: 9450,
    status: 'Unavailable (locked)' as Status,
    categories: ['Development'],
    requires: ['avaj-launcher'],
    unlocks: ['fix-me'],
    isRoot: false,
    topic: `The second Java project: develop GUI applications with the SWING framework to create an RPG game.`,
    catInferred: false,
  },
  {
    id: 1381,
    name: 'taskmaster',
    slug: 'taskmaster',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Devops", "System & Kernel'],
    requires: ['Exam Rank 06'],
    unlocks: ['matt-daemon'],
    isRoot: false,
    topic: `A job control task, in any language, very close to the supervisor program on your computer.`,
    catInferred: false,
  },
  {
    id: 2097,
    name: 'tinky-winkey',
    slug: 'tinky-winkey',
    xp: 16800,
    status: 'Available' as Status,
    categories: ['Security'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Introduction to Windows operating systems by creating a service that runs a keylogger.`,
    catInferred: false,
  },
  {
    id: 1460,
    name: 'total-perspective-vortex',
    slug: 'total-perspective-vortex',
    xp: 9450,
    status: 'Not recommended' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['dslr'],
    unlocks: [''],
    isRoot: false,
    topic: `Learn to use python tools to process large-dimension data, and create a man-machine interface using brainwaves.`,
    catInferred: false,
  },
  {
    id: 2702,
    name: 'tree_nity',
    slug: 'tree-nity',
    xp: 10042,
    status: 'Unavailable (locked)' as Status,
    categories: ['System & Kernel'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Build a message queue system with topics, producers, and consumers, handling IPC, concurrency, and efficient data structures for asynchronous, event-driven communication.`,
    catInferred: true,
  },
  {
    id: 1933,
    name: 'tweets [DEPRECATED]',
    slug: 'tweets-deprecated',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data'],
    requires: ['?1119'],
    unlocks: [''],
    isRoot: false,
    topic: `An introduction to natural language processing: bag of words, TFIDF, stemming, lemmatization, stop-words, cosine similarity, n-grams, word2vec.`,
    catInferred: true,
  },
  {
    id: 1456,
    name: 'userspace_digressions',
    slug: 'userspace-digressions',
    xp: 16800,
    status: 'Not recommended' as Status,
    categories: ['System & Kernel'],
    requires: ['little-penguin-1'],
    unlocks: [''],
    isRoot: false,
    topic: `Make your own userspace init binary.`,
    catInferred: false,
  },
  {
    id: 1444,
    name: 'war',
    slug: 'war',
    xp: 35700,
    status: 'Unavailable (locked)' as Status,
    categories: ['Security'],
    requires: ['pestilence'],
    unlocks: ['death'],
    isRoot: false,
    topic: `Third virus project: reuse Pestilence, having your binary modify its signature at runtime.`,
    catInferred: false,
  },
  {
    id: 1332,
    name: 'webserv',
    slug: 'webserv',
    xp: 21630,
    status: 'Done' as Status,
    categories: ['Core Curriculum'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `This project aims to create your own HTTP server, testable with a real web browser. HTTP is one of the most used protocols on the internet.`,
    catInferred: false,
  },
  {
    id: 1419,
    name: 'woody-woodpacker',
    slug: 'woody-woodpacker',
    xp: 9450,
    status: 'Available' as Status,
    categories: ['Security'],
    requires: ['nm'],
    unlocks: ['famine", "ft_shield'],
    isRoot: false,
    topic: `A logical follow-up to nm/otool: modify the headers of an ELF64 file, adding a chunk of code and hiding a non-stripped part of a file.`,
    catInferred: false,
  },
  {
    id: 1408,
    name: 'xv',
    slug: 'xv',
    xp: 22000,
    status: 'Not recommended' as Status,
    categories: ['Graphics & Gaming'],
    requires: ['in-the-shadows'],
    unlocks: ['freddie-mercury'],
    isRoot: false,
    topic: `Designed by the Daher company: develop a graphic interface under Unity for optimizing industrial processes.`,
    catInferred: false,
  },
  {
    id: 1463,
    name: 'zappy',
    slug: 'zappy',
    xp: 25200,
    status: 'Available' as Status,
    categories: ['Algo & AI & Data", "System & Kernel", "Graphics & Gaming'],
    requires: [''],
    unlocks: [''],
    isRoot: true,
    topic: `Create a multi-player game in a TCP/IP network: a server managing the game field, a graphic client displaying board state, and AI clients piloting players. A complete project for creativity on top of technical knowledge.`,
    catInferred: false,
  },
]

export const fmt = (n: number) => (n ? n.toLocaleString('en-US') : '—')

export const totalXp = (list: Project[]) => list.reduce((a, p) => a + p.xp, 0)

export const getProject = (slug: string) => projects.find((p) => p.slug === slug)

export const byName = (name: string) => projects.find((p) => p.name === name)

export function neighbors(slug: string) {
  const i = projects.findIndex((p) => p.slug === slug)
  if (i === -1) return { prev: undefined, next: undefined }
  return {
    prev: projects[(i - 1 + projects.length) % projects.length],
    next: projects[(i + 1) % projects.length],
  }
}
